name: Performance Tests
description: Runs tests with the performance label

runs:
  using: "composite"
  steps:
  - name: Testing - performance tests
    shell: bash
    run: make install-test-tools run-performance-tests
  - uses: ./.github/workflows/composite-actions/upload-artifact
    if: ${{ failure() }}
    with:
      name: performance-dump
      path: "_output/performance-artifacts"