apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: example-gateway
  namespace: infra
spec:
  gatewayClassName: example-gateway-class
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
  namespace: infra
  # Policy override annotation is missing
spec:
  parentRefs:
  - name: example-gateway
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /a
    backendRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "*"
      namespace: a-root
---
apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: example-opt
  namespace: infra
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
  options:
    faults:
      abort:
        percentage: 100
        httpStatus: 418
    cors:
      exposeHeaders:
        - example
      allowOrigin:
        - example
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
  namespace: infra
spec:
  selector:
    test: test
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-a-root
  namespace: a-root
  annotations:
    delegation.gateway.solo.io/enable-policy-overrides: "headerManipulation,faults"
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /a/1
    backendRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: "*"
      namespace: a
---
apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: route-a-root-opt
  namespace: a-root
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: route-a-root
  options:
    headerManipulation:
      requestHeadersToRemove: ["foo"]
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: route-a
  namespace: a
spec:
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /a/1
    backendRefs:
    - name: svc-a
      port: 8080
---
apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: route-a-opt
  namespace: a
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: route-a
  options:
    headerManipulation:
      requestHeadersToRemove: ["override"]
    cors:
      exposeHeaders:
        - foo
      allowOrigin:
        - baz
---
apiVersion: v1
kind: Service
metadata:
  name: svc-a
  namespace: a
spec:
  ports:
    - protocol: TCP
      port: 8080
