---
#system namespace
apiVersion: v1
kind: Namespace
metadata:
  name: gloo-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: upstreams.gloo.solo.io
spec:
  group: gloo.solo.io
  names:
    kind: Upstream
    listKind: UpstreamList
    plural: upstreams
    singular: upstream
  scope: Namespaced
  version: v1
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualservices.gloo.solo.io
spec:
  group: gloo.solo.io
  names:
    kind: VirtualService
    listKind: VirtualServiceList
    plural: virtualservices
    singular: virtualservice
  scope: Namespaced
  version: v1
##########################
#                        #
#                        #
#         Gloo           #
#                        #
#                        #
##########################
---
#rbac for gloo
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["gloo.solo.io/v1"]
  resources: ["upstreams", "virtualservices"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-cluster-admin-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: gloo-system
roleRef:
  kind: ClusterRole
  name: gloo-role
  apiGroup: rbac.authorization.k8s.io
---
# gloo pod
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    gloo: control-plane
  name: gloo
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        gloo: control-plane
    spec:
      containers:
      - image: soloio/gloo:v0.1.1-debug
        name: gloo
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        command: ["/gloo"]
        args:
        - "--storage.type=kube"
        - "--storage.refreshrate=1m"
        - "--secrets.type=kube"
        - "--secrets.refreshrate=1m"
        - "--xds.port=8081"
        - "--kube.namespace=gloo-system"
---
# gloo service
apiVersion: v1
kind: Service
metadata:
  name: gloo
  labels:
    gloo: control-plane
  namespace: gloo-system
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    gloo: control-plane







##########################
#                        #
#                        #
#         Envoy          #
#                        #
#                        #
##########################
---
# envoy deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    gloo: ingress
  name: ingress
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: ingress
  replicas: 1
  template:
    metadata:
      labels:
        gloo: ingress
    spec:
      initContainers:
      - name: assignnodeid
        image: busybox
        command:
        - sed
        - s/NODE_ID_PLACE_HOLDER/$(POD_NAME).$(POD_NAMESPACE)/
        - -i
        - "/config/envoy.yaml"
        volumeMounts:
        - name: envoy-config
          mountPath: /config
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      containers:
      - image: soloio/envoy:v0.1.1
        name: envoy
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        - containerPort: 19000
          name: admin
        command: ["envoy"]
        args: ["-c", "/config/envoy.yaml", "--v2-config-only"]
        volumeMounts:
        - name: envoy-config
          mountPath: /config
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: ingress
  labels:
    gloo: ingress
  namespace: gloo-system
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  - port: 8443
    protocol: TCP
    name: https
  selector:
    gloo: ingress
  type: NodePort

---
# envoy configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: gloo-system
data:
  envoy.yaml: |
    node:
      cluster: ingress
      id: NODE_ID_PLACE_HOLDER

    static_resources:
      clusters:

      - name: xds_cluster
        connect_timeout: 5.000s
        hosts:
        - socket_address:
            address: gloo.gloo-system.svc.cluster.local
            port_value: 8081
        http2_protocol_options: {}
        type: STRICT_DNS

    dynamic_resources:
      ads_config:
        api_type: GRPC
        cluster_names:
        - xds_cluster
      cds_config:
        ads: {}
      lds_config:
        ads: {}

    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 19000





##########################
#                        #
#                        #
#         Discovery      #
#         Services       #
#                        #
##########################


---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    gloo: k8s-service-discovery
  name: k8s-service-discovery
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: k8s-service-discovery
  replicas: 1
  template:
    metadata:
      labels:
        gloo: k8s-service-discovery
    spec:
      containers:
      - image: soloio/gloo-k8s-service-discovery:v0.1
        name: k8s-service-discovery
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        args:
        - "--storage.type=kube"
        - "--storage.refreshrate=30m"
        - "--kube.namespace=gloo-system"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    gloo: function-discovery
  name: function-discovery
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: function-discovery
  replicas: 1
  template:
    metadata:
      labels:
        gloo: function-discovery
    spec:
      containers:
      - image: soloio/gloo-function-discovery:v0.1.1
        name: function-discovery
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        command: ["/gloo-function-discovery"]
        args:
        - "--storage.type=kube"
        - "--storage.refreshrate=30m"
        - "--secrets.type=kube"
        - "--secrets.refreshrate=30m"
        - "--kube.namespace=gloo-system"







##########################
#                        #
#      Kubernetes        #
#      Ingress           #
#      Controller        #
#                        #
##########################

---
# ingress controller deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    gloo: ingress-controller
  name: ingress-controller
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: ingress-controller
  replicas: 1
  template:
    metadata:
      labels:
        gloo: ingress-controller
    spec:
      containers:
      - image: soloio/kube-ingress-controller:v0.1
        name: ingress-controller
        env:
        - name: DEBUG
          value: "1"
        - name: GRPC_TRACE
          value: all
        command: ["/kube-ingress-controller"]
        args:
        - "--service=envoy"
        - "--storage.refreshrate=30m"
        - "--storage.type=kube"
        - "--kube.namespace=gloo-system"
