version: 2
before:
  hooks:
    - go mod tidy
    - go mod download
builds:
  - id: controller
    main: ./cmd/kgateway
    binary: kgateway-linux-{{ .Arch }}
    gcflags: "{{ .Env.GCFLAGS }}"
    ldflags: "{{ .Env.LDFLAGS }}"
    env:
    - CGO_ENABLED=0
    - GO111MODULE=on
    - GOARCH={{ .Arch }}
    - GOOS={{ .Os }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: sds
    main: ./cmd/sds
    binary: sds-linux-{{ .Arch }}
    gcflags: "{{ .Env.GCFLAGS }}"
    ldflags: "{{ .Env.LDFLAGS }}"
    env:
    - CGO_ENABLED=0
    - GO111MODULE=on
    - GOARCH={{ .Arch }}
    - GOOS={{ .Os }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: envoyinit
    main: ./cmd/envoyinit
    binary: envoyinit-linux-{{ .Arch }}
    gcflags: "{{ .Env.GCFLAGS }}"
    ldflags: "{{ .Env.LDFLAGS }}"
    env:
    - CGO_ENABLED=0
    - GO111MODULE=on
    - GOARCH={{ .Arch }}
    - GOOS={{ .Os }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates:
      - &controller_arm_image "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.CONTROLLER_IMAGE_REPO }}:{{ .Env.VERSION }}-arm64"
    use: buildx
    dockerfile: &controller_dockerfile cmd/kgateway/Dockerfile
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--build-arg=GOARCH=arm64"
      - "--build-arg=ENVOY_IMAGE={{ .Env.ENVOY_IMAGE }}"
  - image_templates:
      - &controller_amd_image "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.CONTROLLER_IMAGE_REPO }}:{{ .Env.VERSION }}-amd64"
    use: buildx
    dockerfile: *controller_dockerfile
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=GOARCH=amd64"
      - "--build-arg=ENVOY_IMAGE={{ .Env.ENVOY_IMAGE }}"
  - image_templates:
      - &sds_arm_image "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.SDS_IMAGE_REPO }}:{{ .Env.VERSION }}-arm64"
    use: buildx
    dockerfile: &sds_dockerfile cmd/sds/Dockerfile
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--build-arg=GOARCH=arm64"
      - "--build-arg=BASE_IMAGE={{ .Env.ALPINE_BASE_IMAGE }}"
  - image_templates:
      - &sds_amd_image "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.SDS_IMAGE_REPO }}:{{ .Env.VERSION }}-amd64"
    use: buildx
    dockerfile: *sds_dockerfile
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=GOARCH=amd64"
      - "--build-arg=BASE_IMAGE={{ .Env.ALPINE_BASE_IMAGE }}"
  - image_templates:
      - &envoyinit_arm_image "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.ENVOYINIT_IMAGE_REPO }}:{{ .Env.VERSION }}-arm64"
    use: buildx
    dockerfile: &envoyinit_dockerfile cmd/envoyinit/Dockerfile.envoyinit
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--build-arg=GOARCH=arm64"
      - "--build-arg=ENTRYPOINT_SCRIPT=/cmd/envoyinit/docker-entrypoint.sh"
      - "--build-arg=ENVOY_IMAGE={{ .Env.ENVOY_IMAGE }}"
    extra_files:
      - cmd/envoyinit/docker-entrypoint.sh
  - image_templates:
      - &envoyinit_amd_image "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.ENVOYINIT_IMAGE_REPO }}:{{ .Env.VERSION }}-amd64"
    use: buildx
    dockerfile: *envoyinit_dockerfile
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=GOARCH=amd64"
      - "--build-arg=ENTRYPOINT_SCRIPT=/cmd/envoyinit/docker-entrypoint.sh"
      - "--build-arg=ENVOY_IMAGE={{ .Env.ENVOY_IMAGE }}"
    extra_files:
      - cmd/envoyinit/docker-entrypoint.sh
docker_manifests:
  - name_template: "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.CONTROLLER_IMAGE_REPO }}:{{ .Env.VERSION }}"
    image_templates:
      - *controller_arm_image
      - *controller_amd_image
  - name_template: "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.SDS_IMAGE_REPO }}:{{ .Env.VERSION }}"
    image_templates:
      - *sds_arm_image
      - *sds_amd_image
  - name_template: "{{ .Env.IMAGE_REGISTRY }}/{{ .Env.ENVOYINIT_IMAGE_REPO }}:{{ .Env.VERSION }}"
    image_templates:
      - *envoyinit_arm_image
      - *envoyinit_amd_image
changelog:
  disable: true
release:
  prerelease: "auto"
  mode: "replace"
  replace_existing_artifacts: true
  header: |
    {{ if eq .Env.VERSION "v2.0.0-main" }}
    🚀 Nightly build of kgateway!
    ---
    It includes the latest changes but may be unstable. Use it for testing and providing feedback.
    {{ else }}
    🎉 Welcome to the {{ .Env.VERSION }} release of the kgateway project!
    ---
    {{ end }}
  footer: |
    ## Installation

    The kgateway project is available as a Helm chart and docker images.

    ### Helm Charts

    The Helm chart is available at {{ .Env.IMAGE_REGISTRY }}/charts/kgateway.

    ### Docker Images

    The docker images are available at:

    - {{ .Env.IMAGE_REGISTRY }}:{{ .Env.CONTROLLER_IMAGE_REPO }}:{{ .Env.VERSION }}
    - {{ .Env.IMAGE_REGISTRY }}:{{ .Env.SDS_IMAGE_REPO }}:{{ .Env.VERSION }}
    - {{ .Env.IMAGE_REGISTRY }}:{{ .Env.ENVOYINIT_IMAGE_REPO }}:{{ .Env.VERSION }}

    ## Quickstart

    For detailed installation instructions and next steps, please visit our [quickstart guide](https://kgateway.dev/docs/quickstart/).
