steps:

# Dep modifies workspace so that the code is moved into the PROJECT_ROOT
- name: 'gcr.io/$PROJECT_ID/dep'
  args: ['ensure']
  env:
    - 'PROJECT_ROOT=github.com/solo-io/gloo'
  id: 'dep'

- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil cp gs://solo-public-artifacts.solo.io/envoy/547421c3922fbfab04ac90a732396c4b9878a052/envoy.stripped /workspace/envoy
    chmod +x /workspace/envoy
  waitFor: ['dep']
  id: 'get-envoy'

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=./gopath/src/github.com/solo-io/gloo/ci/aws_credentials.enc
  - --plaintext-file=/workspace/aws_credentials
  - --location=global
  - --keyring=build
  - --key=build-key
  waitFor: ['dep']
  id: 'setup-aws-creds'

# Helm related setup
- name: gcr.io/cloud-builders/gsutil
  entrypoint: mkdir
  args: ['-p', './_output/helm']
  dir: './gopath/src/github.com/solo-io/gloo'
# sync helm repo data from google cloud bucket
- name: gcr.io/cloud-builders/gsutil
  args:
    - rsync
    - -r
    - gs://solo-public-helm/
    - './_output/helm'
  dir: './gopath/src/github.com/solo-io/gloo'


- name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
  entrypoint: mkdir
  args: ['/workspace/.docker']
  id: 'create-docker-creds-dir'

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=./gopath/src/github.com/solo-io/gloo/ci/dockerhub_credentials.enc
  - --plaintext-file=/workspace/.docker/config.json
  - --location=global
  - --keyring=build
  - --key=build-key
  waitFor: ['dep', 'create-docker-creds-dir']
  id: 'setup-docker-creds'

# e2e-ginkgo is produced from https://github.com/solo-io/cloud-builders/e2e-ginkgo
# sets up redis, consul, kubectl, go with required environment variables
# need to use the provided entrypoint
# Must set the GOPATH to tell the container the workspace has already been set up (by the dep step above)
- name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
  env:
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'GOPATH=/workspace/gopath'
  dir: './gopath/src/github.com/solo-io/gloo'
  entrypoint: make
  args: ['check-format']
  waitFor: ['dep']

- name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
  env:
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'GOPATH=/workspace/gopath'
  - 'ENVOY_BINARY=/workspace/envoy'
  - 'AWS_SHARED_CREDENTIALS_FILE=/workspace/aws_credentials'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster'
  - 'RUN_KUBE_TESTS=1'
  - 'DOCKER_CONFIG=/workspace/.docker/'
  dir: './gopath/src/github.com/solo-io/gloo'
  args: ['-r', '-failFast']
  waitFor: ['get-envoy', 'setup-aws-creds', 'setup-docker-creds']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username soloiobot --password $$DOCKER_HUB_PASSWORD']
  secretEnv: ['DOCKER_HUB_PASSWORD']

- name: 'gcr.io/$PROJECT_ID/go-make'
  args: ['docker']
  env:
    - 'PROJECT_ROOT=github.com/solo-io/gloo'
    - 'GOPATH=/workspace/gopath'
    - 'TAGGED_VERSION=$TAG_NAME'
  dir: './gopath/src/github.com/solo-io/gloo'
  id: 'compile'

- name: 'gcr.io/$PROJECT_ID/go-make'
  args: ['docker-push', 'release', 'deploy-site', 'manifest']
  env:
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'GOPATH=/workspace/gopath'
  - 'HELM_HOME=/root/.helm' # tell helm where to find data
  dir: './gopath/src/github.com/solo-io/gloo'
  secretEnv: ['GITHUB_TOKEN', 'FIREBASE_TOKEN']
  id: 'release'

# Sync helm chart data back to google storage bucket
- name: gcr.io/cloud-builders/gsutil
  args:
    - rsync
    - -r
    - './_output/helm'
    - gs://solo-public-helm/
  dir: './gopath/src/github.com/solo-io/gloo'
  id: 'set-helm-chart'


secrets:
- kmsKeyName: projects/solo-public/locations/global/keyRings/build/cryptoKeys/build-key
  secretEnv:
    GITHUB_TOKEN: CiQABlzmSRpjt9c2jcCGU2lIk68qAkHIzIHUeYS+artlcens/7oSUQCCPGSG407g5usGvAhM+oL98Xir0fHWUiNe3827h9zdhmkCbrZpNqfVFkMhAxQ/ZlhC31+KwzWoHnDSb3RN7CoKj+gves6q7MMf7wNxSmC46A==
    DOCKER_HUB_PASSWORD: CiQABlzmSW0u+qhXDvTCxLnbi09Zm88eCU0wSdvFn1W+6WOpTgQSTgCCPGSGTAlMndrEkYOynPhDzTXrW1q1eAsQYjKOWOwZKodcQZ2WIzdvpOOjv+WrGTssWWg1uPFV4CnajT7DzeNAb7USkla1epatm6OnuQ==
    FIREBASE_TOKEN: CiQABlzmSc0BWpPfrGRtDscrxOfp9ZBkZO9fkO79tjEmA14c8ZESVwCCPGSG8uZtLSmFucmEEJGJ0080ON7Zw5TjLe2YdwuxnSOA5YzZryVwLFAMzRmfb6OBxyThTZKvGZzgfXyv6CeLwYX0exk20u7k2bnrWbFHO0Aa4TiQqw==

timeout: 6600s
