steps:

- name: 'gcr.io/cloud-builders/wget'
  entrypoint: ./ci/spell.sh
  args: ['check']
  waitFor: ['-']
  env:
  # The LSCOMMAND is the env var which tells the spell script how to search for the files it needs to fix.
  - 'LSCOMMAND=find * -type f | grep -v vendor | grep -v docs/themes | grep -v docs/site'
  id: 'check-spelling'

- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args: ['-c', 'mkdir -p /go/pkg && cd /go/pkg && gsutil cat gs://$PROJECT_ID-cache/gloo/gloo-mod.tar.gz | tar -xzf -']
  id: 'untar-mod-cache'

# TODO: during this step, prepare-workspace to set up the project so it can be built and tested
# Dep modifies workspace so that the code is moved into the PROJECT_ROOT
# All steps after this must set GOPATH
- name: 'gcr.io/$PROJECT_ID/prepare-go-workspace:0.2.2'
  args:
  - "--repo-owner"
  - "solo-io"
  - "--repo-name"
  - gloo
  - "--repo-sha"
  - "$COMMIT_SHA"
  - "--repo-output-dir"
  - "."
  env:
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'GIT_SSH_CONFIG=FALSE'
  id: 'prepare-workspace'


# Run some basic checks on the repo
# 1) check formatting of go files
# 2) ensure that make generated-code produces a clean diff
# 3) ensure that the site is generated with no warnings (strict = true in mkdocs)

# e2e-go-mod-ginkgo is produced from https://github.com/solo-io/cloud-builders/e2e-go-mod-ginkgo
# Must set the GOPATH to tell the container the workspace has already been set up (by the dep step above)
- name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.2.1'
  env:
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  dir: &dir '/workspace/gloo'
  entrypoint: make
  args: ['check-format']
  waitFor: ['prepare-workspace']
  id: 'check-format'
- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.1'
  entrypoint: 'bash'
  args: ['ci/check-code-and-docs-gen.sh']
  env:
  - 'TAGGED_VERSION=$TAG_NAME'
  dir: *dir
  waitFor: ['prepare-workspace']
  id: 'check-code-and-docs-gen'

# Run all the tests with ginkgo -r -failFast -trace -progress --noColor
# This requires setting up envoy, AWS, helm, and docker
# The e2e-go-mod-ginkgo container provides everything else needed for running tests
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    ENVOY_VERSION=v$$(head -n1 ./projects/envoyinit/cmd/Dockerfile.envoyinit|cut -d: -f2)
    gsutil cp gs://solo-public-artifacts.solo.io/envoy/$$ENVOY_VERSION/envoy.stripped /workspace/envoy
    chmod +x /workspace/envoy
  waitFor: ['prepare-workspace']
  dir: *dir
  id: 'get-envoy'
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=./ci/aws_credentials.enc
  - --plaintext-file=/workspace/aws_credentials
  - --location=global
  - --keyring=build
  - --key=build-key
  waitFor: ['prepare-workspace']
  dir: *dir
  id: 'setup-aws-creds'
# Helm related setup
- name: gcr.io/cloud-builders/gsutil
  entrypoint: mkdir
  args: ['-p', './_output/helm']
  dir: *dir
  waitFor: ['prepare-workspace']
  id: 'make-helm-dir'
- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.1'
  args: ['fetch-helm']
  env:
    - 'PROJECT_ROOT=github.com/solo-io/gloo'
    - 'TAGGED_VERSION=$TAG_NAME'
  dir: *dir
  id: 'fetch-helm'
  waitFor: ['prepare-workspace']
# Docker related setup
# grab this container immediately in parallel
- name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.2.1'
  entrypoint: ls
  waitFor: ['-']
  id: 'grab-ginkgo-container'

- name: gcr.io/cloud-builders/gcloud
  args: ['config', 'set', 'compute/zone', 'us-central1-a']
  id: 'set-test-zone'
  # run after dep so it doesn't move our settings
  waitFor: ['prepare-workspace']
- name: gcr.io/cloud-builders/gcloud
  args: ['container', 'clusters', 'get-credentials', 'test-cluster-roles']
  id: 'get-test-credentials'
  waitFor: ['set-test-zone']

- name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.2.1'
  env:
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'ENVOY_BINARY=/workspace/envoy'
  - 'AWS_SHARED_CREDENTIALS_FILE=/workspace/aws_credentials'
  - 'RUN_KUBE_TESTS=1'
  - 'RUN_CONSUL_TESTS=1'
  - 'RUN_VAULT_TESTS=1'
  - 'DOCKER_CONFIG=/workspace/.docker/'
  - 'HELM_HOME=/root/.helm'
  dir: *dir
  args: ['-r', '-failFast', '-trace', '-progress', '-race', '-compilers=10', '--noColor']
  waitFor: ['get-envoy', 'setup-aws-creds', 'fetch-helm', 'check-code-and-docs-gen', 'set-test-zone', 'get-test-credentials']
  secretEnv: ['AWS_ARN_ROLE_1']
  id: 'test'

# Build and tag docker images
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  env:
  - 'DOCKER_CONFIG=/workspace/docker-config'
  args: ['-c', 'docker login quay.io --username "solo-io+solobot" --password $$QUAY_IO_PASSWORD']
  secretEnv: ['QUAY_IO_PASSWORD']
  id: 'docker-login'
  waitFor: ['prepare-workspace']
- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.1'
  args: ['docker']
  env:
    - 'PROJECT_ROOT=github.com/solo-io/gloo'
    - 'TAGGED_VERSION=$TAG_NAME'
    - 'BUILD_ID=$BUILD_ID'
    - 'GCLOUD_PROJECT_ID=$PROJECT_ID'
  dir: *dir
  waitFor: ['prepare-workspace', 'check-code-and-docs-gen']
  id: 'compile'

  # 1) Run make targets to push docker images
- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.1'
  args: ['docker-push']
  env:
  - 'DOCKER_CONFIG=/workspace/docker-config'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'HELM_HOME=/root/.helm' # tell helm where to find data
  dir: *dir
  secretEnv: ['GITHUB_TOKEN']
  waitFor: ['compile']
  id: 'docker-push'
# 2) Publish helm chart, compile manifests, produce release artifacts, deploy docs
# isolating this portion of the release in order to force the manifest to be regenerated with the tagged version
- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.1'
  args: ['package-chart', 'render-manifests', 'upload-github-release-assets', 'download-glooe-changelog', 'publish-docs', '-B']
  env:
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'GCLOUD_PROJECT_ID=$PROJECT_ID'
  - 'HELM_HOME=/root/.helm' # tell helm where to find data
  dir: *dir
  secretEnv: ['GITHUB_TOKEN']
  waitFor: ['compile']
  id: 'release-chart'

- name: gcr.io/cloud-builders/gcloud
  args: ['config', 'set', 'compute/zone', 'us-central1-a']
  id: 'set-regression-zone'
  # run after dep so it doesn't move our settings
  waitFor: ['test']
# Run regression tests
- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.1'
  args: ['build-test-assets']
  env:
    - 'PROJECT_ROOT=github.com/solo-io/gloo'
    - 'BUILD_ID=$BUILD_ID'
    - 'GCLOUD_PROJECT_ID=$PROJECT_ID'
    - 'HELM_HOME=/root/.helm'
    - 'TAGGED_VERSION=$TAG_NAME'
  dir: *dir
  waitFor: ['compile', 'docker-login', 'docker-push', 'test']
  id: 'build-test-assets'

- name: gcr.io/cloud-builders/gcloud
  env:
  - 'KUBECONFIG=/workspace/kube-e2e'
  args: ['container', 'clusters', 'get-credentials', 'kube2e-tests']
  id: 'get-regression-credentials'
  # wait for dep so our kube config is not moved.
  waitFor: ['set-regression-zone', 'prepare-workspace']

- name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.2.1'
  env:
    - 'PROJECT_ROOT=github.com/solo-io/gloo'
    - 'RUN_KUBE2E_TESTS=1'
  dir: *dir
  args: ['-r', '--noColor', '-failFast', '-trace', '-progress', 'test/kube2e']
  waitFor: ['build-test-assets', 'set-regression-zone']
  id: 'regression-tests'


- name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.2.1'
  env:
    - 'KUBECONFIG=/workspace/kube-e2e'
    - 'PROJECT_ROOT=github.com/solo-io/gloo'
    - 'RUN_KUBE2E_TESTS=1'
    - 'CLUSTER_LOCK_TESTS=1'
  dir: *dir
  args: ['-r', '--noColor', '-failFast', '-trace', '-progress', 'test/kube2e']
  waitFor: ['build-test-assets', 'get-regression-credentials']
  id: 'regression-tests-cluster-lock'

# 3) Sync helm chart data back to google storage bucket
- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.1'
  args: ['save-helm']
  env:
    - 'PROJECT_ROOT=github.com/solo-io/gloo'
    - 'TAGGED_VERSION=$TAG_NAME'
  dir: *dir
  id: 'save-helm-chart'

secrets:
- kmsKeyName: projects/solo-public/locations/global/keyRings/build/cryptoKeys/build-key
  secretEnv:
    GITHUB_TOKEN: CiQABlzmSYYiveU0gTxGH2139eaBUedjV3vNCxQmJU+nRPlfQ/YSUQCCPGSGzbGp49fwDYuefAx9V94b8mivdp9AqB7zQAa07VtGJmrGdg9ZuhKGFrrgqxwABE0LLVNHyngCSHYSYMH8Vn/mRtT7wQuEHBlKVGtqPw==
    QUAY_IO_PASSWORD: CiQABlzmSRx5TcOqbldXa/d/+bkmAfpNAWa3PTS06WvuloZL+vASaQCCPGSGCogonVZVEUNx4G3YJtWi18gSuNx4PvLe08q8xAflTMFkjsyQirAOK3Y2oCvgYwiw/ITcuydjkpMjxDygFyENXS9FKFJoAXHlPQE5qidKr8xxmxF5ezhmjGB0gjyjXIIkbSEnBg==
    AWS_ARN_ROLE_1: CiQABlzmSTKWrIEGaH8UvsX3Wp8pz8ClQODVSjIZAiHuE9gNhM4SXACCPGSGCDSNJtdfkA0BLLmKTJLIM06XXEOV4iIooqlLfo9p7EOzOwqZaV9DFygO8/oKQqTFstc1vKgOz7YHrMaCx3GzqiHN2u//UmHRpvIwrDDfuIP5XNa0aOrj

timeout: 5400s
tags: ['gloo']
options:
  machineType: 'N1_HIGHCPU_32'
  volumes:
  - name: 'gopath'
    path: '/go'
