options:
  env:
    - "_GO_VERSION=1.23.3"

steps:
- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args: ['-c', 'mkdir -p /go/pkg && cd /go/pkg && gsutil cat gs://$PROJECT_ID-cache/gloo/gloo-mod.tar.gz | tar -xzf -']
  env:
  volumes: &vol
  - name: 'gopath'
    path: '/go/pkg'
  id: 'untar-mod-cache'

- name: 'golang:${_GO_VERSION}'
  entrypoint: 'bash'
  args:
    - '-c'
    - 'go mod download && go mod tidy && cd /go/pkg && tar -zvcf gloo-mod.tar.gz mod'
  volumes: *vol
  id: 'download-tidy-cache'

- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '/go/pkg/gloo-mod.tar.gz', 'gs://$PROJECT_ID-cache/gloo/gloo-mod.tar.gz']
  volumes: *vol
  id: 'upload-cache'
