steps:

# Dep modifies workspace so that the code is moved into the PROJECT_ROOT
- name: 'gcr.io/$PROJECT_ID/dep'
  args: ['ensure']
  env:
    - 'PROJECT_ROOT=github.com/solo-io/gloo'
  id: 'dep'

- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gsutil cp gs://solo-public-artifacts.solo.io/envoy/547421c3922fbfab04ac90a732396c4b9878a052/envoy.stripped /workspace/envoy
    chmod +x /workspace/envoy
  waitFor: ['dep']
  id: 'get-envoy'

- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=./gopath/src/github.com/solo-io/gloo/ci/aws_credentials.enc
  - --plaintext-file=/workspace/aws_credentials
  - --location=global
  - --keyring=build
  - --key=build-key
  waitFor: ['dep']
  id: 'setup-aws-creds'

# e2e-ginkgo is produced from https://github.com/solo-io/cloud-builders/e2e-ginkgo
# sets up redis, consul, kubectl, go with required environment variables
# need to use the provided entrypoint

# Must set the GOPATH to tell the container the workspace has already been set up (by the dep step above)
- name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
  env:
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'GOPATH=/workspace/gopath'
  dir: './gopath/src/github.com/solo-io/gloo'
  entrypoint: make
  args: ['check-format']
  waitFor: ['dep']

- name: 'gcr.io/$PROJECT_ID/e2e-ginkgo'
  env:
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'GOPATH=/workspace/gopath'
  - 'ENVOY_BINARY=/workspace/envoy'
  - 'AWS_SHARED_CREDENTIALS_FILE=/workspace/aws_credentials'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test-cluster'
  - 'RUN_KUBE_TESTS=1'
  dir: './gopath/src/github.com/solo-io/gloo'
  args: ['-r', '-failFast']
  waitFor: ['get-envoy', 'setup-aws-creds']

- name: 'gcr.io/$PROJECT_ID/go-make'
  args: ['release']
  env:
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'PROJECT_ROOT=github.com/solo-io/gloo'
  - 'GOPATH=/workspace/gopath'
  dir: './gopath/src/github.com/solo-io/gloo'
  secretEnv: 'GITHUB_TOKEN'
secrets:
- kmsKeyName: projects/solo-public/locations/global/keyRings/build/cryptoKeys/build-key
  secretEnv:
    GITHUB_TOKEN: CiQABlzmSRpjt9c2jcCGU2lIk68qAkHIzIHUeYS+artlcens/7oSUQCCPGSG407g5usGvAhM+oL98Xir0fHWUiNe3827h9zdhmkCbrZpNqfVFkMhAxQ/ZlhC31+KwzWoHnDSb3RN7CoKj+gves6q7MMf7wNxSmC46A==

timeout: 1800s