
steps:
# Setup SSH
# These are required before dep
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=ci/id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=build
  - --key=build-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'get-ssh-key'
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv ./ci/github_known_hosts /root/.ssh/known_hosts
    git config --global url."ssh://git@github.com/solo-io".insteadOf https://github.com/solo-io
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  id: 'configure-git'

- name: gcr.io/cloud-builders/gsutil
  entrypoint: 'bash'
  args: ['-c', 'mkdir -p /go/pkg && cd /go/pkg && gsutil cat gs://$PROJECT_ID-cache/solo-projects/solo-projects-mod.tar.gz | tar -xzf -']
  env:
  volumes: &vol
  - name: 'gopath'
    path: '/go/pkg'
  - name: 'ssh'
    path: /root/.ssh
  id: 'untar-mod-cache'

- name: 'golang:${_GO_VERSION}'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      go env -w GOPRIVATE=github.com/solo-io && \
      go mod download && \
      go mod tidy && \
      cd /go/pkg && tar -zvcf solo-projects-mod.tar.gz mod
  volumes: *vol
  id: 'update-and-cache-tar'

- name: gcr.io/cloud-builders/gsutil
  args: ['cp', '/go/pkg/solo-projects-mod.tar.gz', 'gs://$PROJECT_ID-cache/solo-projects/solo-projects-mod.tar.gz']
  volumes: *vol
  id: 'upload-cache'

options:
  env:
  - "GO111MODULE=on"
  - "_GO_VERSION=1.20.1"