steps:

- name: 'gcr.io/$PROJECT_ID/prepare-go-workspace:0.8.1'
  id: 'prepare-workspace'
  args:
  - '--repo-name'
  - '$REPO_NAME'
  - '--repo-sha'
  - '$COMMIT_SHA'
  - '--repo-output-dir'
  - '.'
  env:
  - 'GIT_SSH_CONFIG=FALSE'

- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  id: 'untar-mod-cache'
  dir: &dir /workspace/gloo
  args:
  - '-c'
  - |
    mkdir -p /go/pkg
    cd /go/pkg
    gsutil cat gs://$PROJECT_ID-cache/gloo/gloo-mod.tar.gz | tar -xzf - || echo "untar mod cache failed; continuing because we can download deps as we need them"

- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.8.1'
  id: 'prepare-envoy'
  dir: *dir
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    { # try to pull release assets first
      ENVOY_VERSION=v$$(make print-ENVOY_GLOO_IMAGE | cut -d: -f2)
      gsutil cp gs://solo-public-artifacts.solo.io/envoy/$$ENVOY_VERSION/envoy.stripped /workspace/envoy
      chmod +x /workspace/envoy
    } || { # if that fails, pull from CI
      ENVOY_VERSION=$$(make print-ENVOY_GLOO_IMAGE | cut -d: -f2)
      gsutil cp gs://solo-public-artifacts.solo.io/envoy/$$ENVOY_VERSION/envoy /workspace/envoy
      chmod +x /workspace/envoy
    }
  waitFor:
  - 'prepare-workspace'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'prepare-aws-creds'
  dir: *dir
  args:
  - 'kms'
  - 'decrypt'
  - '--ciphertext-file=./ci/aws_credentials.enc'
  - '--plaintext-file=/workspace/aws_credentials'
  - '--location=global'
  - '--keyring=build'
  - '--key=build-key'
  waitFor:
  - 'prepare-workspace'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'prepare-gcr-zone'
  args:
  - 'config'
  - 'set'
  - 'compute/zone'
  - 'us-central1-a'

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'prepare-test-credentials'
  args:
  - 'container'
  - 'clusters'
  - 'get-credentials'
  - 'test-cluster-roles'
  waitFor:
  - 'prepare-gcr-zone'

- name: 'gcr.io/$PROJECT_ID/go-mod-make:0.8.1'
  id: 'prepare-test-tools'
  dir: *dir
  args:
  - 'install-test-tools'
  waitFor:
  - 'prepare-envoy'
  - 'prepare-aws-creds'
  - 'prepare-gcr-zone'
  - 'prepare-test-credentials'

- name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.8.1'
  id: 'run-tests'
  dir: *dir
  entrypoint: 'make'
  args:
  - 'run-tests'
  waitFor:
  - 'prepare-test-tools'
  secretEnv:
  - 'JWT_PRIVATE_KEY'

- name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.8.1'
  id: 'run-e2e-tests'
  dir: *dir
  entrypoint: 'make'
  args:
  - 'run-e2e-tests'
  waitFor:
  - 'prepare-test-tools'
  secretEnv:
  - 'JWT_PRIVATE_KEY'

- name: 'gcr.io/$PROJECT_ID/e2e-go-mod-ginkgo:0.8.1'
  id: 'run-hashicorp-e2e-tests'
  dir: *dir
  entrypoint: 'make'
  args:
    - 'run-hashicorp-e2e-tests'
  waitFor:
    - 'prepare-test-tools'
  secretEnv:
    - 'JWT_PRIVATE_KEY'

secrets:
- kmsKeyName: 'projects/solo-public/locations/global/keyRings/build/cryptoKeys/build-key'
  secretEnv:
    JWT_PRIVATE_KEY: 'CiQABlzmSSG8GDGXqdDoYk9AITZ4fPYsrajkHZNw7vGWr+DmpfsS6hEAgjxkhm7xnuDUuEv423kS8L0YdXrkF2vfCTpW1CXVQb/sIwO0Nk6WA6RmqKwlG2rFq+LlPkVxZtCFba56ElZDhy5oTJ0PibIOzoQLh5QE4tq7U0pS5gdg7vAJ9mo26PqMQW7zebfrdLnlBtNjocbpHLeUl9WQNVnk95UIw07jVEirV85GrR+Zo5vjXXXgoF+gRyMGg8hRmutN2SmUF3LO3NcRLvsC24htKk+2ryQyzwZ7pqB0y7YJkDcr7KPJcAyQsTTr5cwbSxxe07Rb7is2qI4VLshEdLvyjJAv0lXQIkybLpDxyEW74M+RS56PYaCDEqICBZ11VKvy5n31rIVZbbsMIAJj8EFrfOZXAZtKgEa1E8LB3FDyVyBxrFcyTCNw3NjqzUIUVJ5ImOrcIyJ3deOsxeIWnF0v07KcLK82nxsDxZqkXjw/qKoMYXr5HGvIEqKb42dLf8OG3k/6vE/e/+TUjKxTrOQQUVbk0MKXiiZpwjVlJmiJgo10Zou3p4W71oMBz6fiWhdUMMi8ynRAy9ZE7zEfra1mwlTYD963PX1Ug2DduejPghR7aCwoQTjfpwHe04DVCWl4zM8mh3pVfELlKJ9ExqkSNtyrVJ6HJWHidySHtMkyITnh3PpT6hPMjefOAJ12jZVkCJiAUmaSl6s7DebCRSEtWq2Ad/pPG6Z2xbfmrsKvlHvG2tu1C8gQprvGjOvl3ot0xCeQc58mt9bz7EdPkph+tLXWT19gkpIB39j65zwtIBEJAsMdh4TZGPiZwm1oDu+4OIzPv5Xmo8TWyJpQGYF1d7yqArzK4hL7FWnuTpSGtEsZpWKXBSHvFMZT7tbXMCkt5cmPtSKE/AMMuj43LBiCgnxVG+qiyB+iDkBQNXXS33Mfk0GtEMzeHK1OMuNviXjL9acMeB0OEFh84323u2ARCm1iD4VkTPpSKSDAdr+olBbhq57emmZxfd6mjiqcOET+rbC5tN2PG8VLc5q9yCQnCw7Bdaw+WbuQpcdC9caRd3ylY4RzDH8+jFq7/3fseuuQ38JUu+jeTEozX4bXO9O8/HMey+rf/6vDtZamfCr6dp2b2W9aTG8YN8985ZPfO28jANbvH911RsR1GK1lT9SCkHwY8ZyNSF3C4yJbt3GQNOwAcux3YKQLh4EFTCggcdHRGYxTvADlW1DwGFEUFV6K4mOKZo99YuUKJ4KyMJkwawhhDT3GmJ8vmpe7HtF9Cjleq2McugihLKmZBnhEHl7haNONWUaZ3JqG/4hV4ZkudVH3R/COJarI2eRU/Lacnjph5YRIgVb43Myp/B62mFTWGcyLdUEnsNsbNAKrWdIrhjnICYlKvqGfhZyOYENzPY4zd8VXxGmuPXbsni1jLGYqG2NpnrkEGvH7csmo4IPuTthkRVPK3lpaLcQV6qwuwCQUIQb2ueO8a9GX5wTosEjjivvgtVqFm3r2ag2wCYxCV95B4u5udVDvJSpaHozYb08T+VKZ2Kt58e1/wTbxmbI3Z7XQV/tL043hNai9+MynSezie70m+pK87iWGQgNKW5bNHB5d2v2IN/uTJ3OH9YHIyjH9gIGl1Yj4ozF09lZeUDxbZ6QINnkqZndWVuLY/lQvQkelJAH9FZvrwQev/LUzScz2BxGKrQRLgqVBHOutUV//tNqDlnHJk954w3MyQ6y1faTukpNiRar57G6KmJ2OSIOFi+Wo5SeBIXmtDu59krxvYTZcbL9UQF+iZaP+sw8ZLXt16qAXBlKN/pF5jD9bZ5BaIo+vxb35wTAim0sd8q+irNDYFngaWfqDHN1dFtTQ5zfmuv/a26b9Lro6+K6NiscdykTAjWXLmSjESNYvqUGcahIWpl0Ll6QdJ2NhFkMGZgkr33yDl4FTGbkeSgfuf5Ou2kDis9QPg4GSjS7hTmSMCcmeawRK6CFC/yLHQoEuipNtK9D1n063FmEZK7ZftsGE7L+TQjn5HHjU78qJ4I7K2oH1cRle+PgWq35zG70VByhpYP9uBJD2f+GEjzCXLTBm05Y4bk1ODEhSCN6GlqGisQcNhA95M7RXXlNTM1K6ZGqUK7KUCLPbpI8j2svv5fqw3ZcZEM51Q0NSUPKS+tEb+yD+OwZ5cQQymLz2H7O5fPQtYyFTnko1sOfVfSpphjebudaL4agZKM2FWrS4SC1qAbDe2ymoQMRybNDTllJIopflit1q0fBQvmkVC3Iu6njsjCLtPSqJ5KBVNwwm3GPG59+kqN3PnogDP64JmOqkpiENmA6k+QHI2DsvYoMkkpXOct9L/+tt2oqiVHUBRkaqFyzt5Do2CSkjpziwyXRmE8e5PrXUli8U/EbohFN7fi6YjY4qQF9XptGUHI0wgMXi+uBbxwWLN/HiAEX7EqQCY7Vpu+u5E4mceTG/M69C/CMtlFGyfPWakWjR8XNBlsawr7edQKupQJ3dW1HZL/lMmAXWiPp4SCEix+IwSdhI2qPYOdbZeCH37CktYzbGRgxdqVifCZOCtQwktjq7beOPJaYGMKC8md/0u6yaUkFmsd8Uu6rw8LbZtqM6T9XSDgCHegouUlP4A/mWF1t35BDZ8IJl9lxtwmXjQkQcjWnOMKTL+2BJ87CHTlgHAOiy5jtNCgF9ZU0qA6R4l15i6avOru58XzVK92CMgEFd67pna69IjpgnYawqi3UiEtArX2Ru5S8IGFe8SSiivvkeFZWkLOQxvhWUFI+7+vpritnt4lwKJua7Yd7GU+i0RJ1Jbvz8eFWFwfLko7okM6WfLDwkTHIWwuPgqTM2Zmaj7ayjZxxFVpEiKFAScVVoUoz1WKz1mEVTh5U/YkQFClDt/cfJLmTKjFeubOiH0nYp8le8JTC58syynU5jnZ3uZ7RnjcAWF0shFCCnxhgp4S7zU0NVE/ZuscpkFhjsGda095Bdmfq/uOO88eFB6ouRop4UqsaTqxV63KZ/7ZICm2N6+w4EC1ra2Ixl76N1Ix6IycvJEMvMSPhTwRDVco0dfvsF++vvhujVeoui7mw15x7g8ZJqXi3ND7mTlWXad2D2bQoUog=='

timeout: '3600s'

tags:
- 'gloo'

options:
  machineType: 'N1_HIGHCPU_32'
  env:
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'TEST_ASSET_ID=$_PR_NUM'
  - 'ENVOY_BINARY=/workspace/envoy'
  - 'AWS_SHARED_CREDENTIALS_FILE=/workspace/aws_credentials'
  - 'RUN_KUBE_TESTS=1'
  - 'RUN_CONSUL_TESTS=1'
  - 'RUN_VAULT_TESTS=1'
  - 'DOCKER_CONFIG=/workspace/.docker/'
  - 'SKIP_TEMP_DISABLED=1' # https://github.com/solo-io/solo-projects/issues/4515
  # Gloo supports running tests in parallel (https://github.com/solo-io/gloo/pull/8423) but occasionally
  # Ginkgo reports a failure, even when all test suites pass. As a result, we do not run tests in parallel in CI.
  - 'GINKGO_USER_FLAGS=-procs=1'
  volumes:
  - name: 'gopath'
    path: '/go'
