name: Static Code Analysis

on: pull_request

jobs:
  codegen:
    name: codegen check
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Prep Go Runner
        uses: ./.github/workflows/composite-actions/prep-go-runner
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Code
        run: |
          ./ci/check-generated-code.sh
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
      - name: Check for DO_NOT_SUBMIT
        # documentation for where we get the list of files to pass into the script:
        # https://github.com/marketplace/actions/changed-files?version=v37#outputs
        run: ./ci/do-not-submit.sh ${{ steps.changed-files.outputs.all_changed_files }}
