workspace(name = "envoy")

local_repository(
    name = "envoy_build_config",
    path = "./build-config",
)

local_repository(
    name = "envoy",
    path = "./envoy",
)

local_repository(
    name = "solo_envoy_common",
    path = "./envoy-common",
)

local_repository(
    name = "transformation_filter",
    path = "../pkg/plugins/common/transformation/envoy",
)

local_repository(
    name = "aws_lambda",
    path = "../pkg/plugins/aws/envoy",
)

local_repository(
    name = "nats_streaming_filter",
    path = "../pkg/plugins/nats-streaming/envoy",
)

local_repository(
    name = "azure_functions_filter",
    path = "../pkg/plugins/azure/envoy",
)

local_repository(
    name = "google_functions",
    path = "../pkg/plugins/google/envoy",
)

local_repository(
    name = "consul_connect_filter",
    path = "../pkg/plugins/connect/envoy",
)

JSON_SHA = "c8ea63a31bbcf652d61490b0ccd86771538f8c6b"

new_http_archive(
    name = "json",
    strip_prefix = "json-" + JSON_SHA + "/single_include/nlohmann",
    url = "https://github.com/nlohmann/json/archive/" + JSON_SHA + ".zip",
    build_file_content = """
cc_library(
    name = "json-lib",
    hdrs = ["json.hpp"],
    visibility = ["//visibility:public"],
)
    """
)

INJA_SHA = "74ad4281edd4ceca658888602af74bf2050107f0"

new_http_archive(
    name = "inja",
    strip_prefix = "inja-" + INJA_SHA + "/src",
    url = "https://github.com/pantor/inja/archive/" + INJA_SHA + ".zip",
    build_file_content = """
cc_library(
    name = "inja-lib",
    hdrs = ["inja.hpp"],
    visibility = ["//visibility:public"],
)
    """
)

# Load envoy stuff:

load("@envoy//bazel:repositories.bzl", "envoy_dependencies")
load("@envoy//bazel:cc_configure.bzl", "cc_configure")

envoy_dependencies()

cc_configure()

load("@envoy_api//bazel:repositories.bzl", "api_dependencies")
api_dependencies()

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
load("@com_lyft_protoc_gen_validate//bazel:go_proto_library.bzl", "go_proto_repositories")
go_proto_repositories(shared=0)
go_rules_dependencies()
go_register_toolchains()
