apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: petstore
  name: petstore
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      app: petstore
  replicas: 1
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - image: soloio/petstore-example:latest
        name: petstore
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: gloo-system
  labels:
    sevice: petstore
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: petstore
---
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: petstore
  namespace: gloo-system
spec:
  virtualHost:
    options:
      cors:
        allowOrigin:
        - "http://localhost:1234" # This will be e.g. dev-portal.solo.io
        allowHeaders:
        - "api-key"
      extauth:
        configRef:
          name: apikey-auth
          namespace: gloo-system
    domains:
    - "localhost:8080" # This will be e.g. pet-store.solo.io
    routes:
    - matchers:
      - prefix: /api
      routeAction:
        single:
          kube:
            port: 8080
            ref:
              name: petstore
              namespace: gloo-system
---
#apiVersion: gateway.solo.io/v1
#kind: VirtualService
#metadata:
#  name: dev-portal
#  namespace: gloo-system
#spec:
#  virtualHost:
#    domains:
#    - "localhost:1234" # This will be e.g. dev-portal.solo.io
#    routes:
#    # route to portal
#    - matchers:
#      - prefix: /
#      routeAction:
#        single:
#          kube:
#            port: 8080
#            ref:
#              name: dev-portal
#              namespace: gloo-system