```yaml
apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: grpc-auth-tutorial
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - 'foo-grpc'
    routes:
      - matchers:
        - prefix: /
        routeAction:
          single:
            upstream:
              name: json-upstream
              namespace: gloo-system
        options:
          autoHostRewrite: true
```