// Code generated by skv2. DO NOT EDIT.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: github.com/solo-io/solo-projects/projects/apiserver/api/fed.rpc/v1/federated_gloo_resources.proto

package v1

import (
	context "context"
	reflect "reflect"
	sync "sync"

	_ "github.com/solo-io/protoc-gen-ext/extproto"
	v11 "github.com/solo-io/skv2/pkg/api/core.skv2.solo.io/v1"
	v1 "github.com/solo-io/solo-projects/projects/apiserver/pkg/api/rpc.edge.gloo/v1"
	types "github.com/solo-io/solo-projects/projects/gloo-fed/pkg/api/fed.gloo.solo.io/v1/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FederatedUpstream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *v1.ObjectMeta                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec     *types.FederatedUpstreamSpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status   *types.FederatedUpstreamStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *FederatedUpstream) Reset() {
	*x = FederatedUpstream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FederatedUpstream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedUpstream) ProtoMessage() {}

func (x *FederatedUpstream) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedUpstream.ProtoReflect.Descriptor instead.
func (*FederatedUpstream) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{0}
}

func (x *FederatedUpstream) GetMetadata() *v1.ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FederatedUpstream) GetSpec() *types.FederatedUpstreamSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *FederatedUpstream) GetStatus() *types.FederatedUpstreamStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type FederatedUpstreamGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *v1.ObjectMeta                      `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec     *types.FederatedUpstreamGroupSpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status   *types.FederatedUpstreamGroupStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *FederatedUpstreamGroup) Reset() {
	*x = FederatedUpstreamGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FederatedUpstreamGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedUpstreamGroup) ProtoMessage() {}

func (x *FederatedUpstreamGroup) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedUpstreamGroup.ProtoReflect.Descriptor instead.
func (*FederatedUpstreamGroup) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{1}
}

func (x *FederatedUpstreamGroup) GetMetadata() *v1.ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FederatedUpstreamGroup) GetSpec() *types.FederatedUpstreamGroupSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *FederatedUpstreamGroup) GetStatus() *types.FederatedUpstreamGroupStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type FederatedSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Metadata *v1.ObjectMeta                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec     *types.FederatedSettingsSpec   `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status   *types.FederatedSettingsStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *FederatedSettings) Reset() {
	*x = FederatedSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FederatedSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederatedSettings) ProtoMessage() {}

func (x *FederatedSettings) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederatedSettings.ProtoReflect.Descriptor instead.
func (*FederatedSettings) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{2}
}

func (x *FederatedSettings) GetMetadata() *v1.ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *FederatedSettings) GetSpec() *types.FederatedSettingsSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *FederatedSettings) GetStatus() *types.FederatedSettingsStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListFederatedUpstreamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFederatedUpstreamsRequest) Reset() {
	*x = ListFederatedUpstreamsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFederatedUpstreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederatedUpstreamsRequest) ProtoMessage() {}

func (x *ListFederatedUpstreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederatedUpstreamsRequest.ProtoReflect.Descriptor instead.
func (*ListFederatedUpstreamsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{3}
}

type ListFederatedUpstreamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FederatedUpstreams []*FederatedUpstream `protobuf:"bytes,1,rep,name=federated_upstreams,json=federatedUpstreams,proto3" json:"federated_upstreams,omitempty"`
}

func (x *ListFederatedUpstreamsResponse) Reset() {
	*x = ListFederatedUpstreamsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFederatedUpstreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederatedUpstreamsResponse) ProtoMessage() {}

func (x *ListFederatedUpstreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederatedUpstreamsResponse.ProtoReflect.Descriptor instead.
func (*ListFederatedUpstreamsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{4}
}

func (x *ListFederatedUpstreamsResponse) GetFederatedUpstreams() []*FederatedUpstream {
	if x != nil {
		return x.FederatedUpstreams
	}
	return nil
}

type GetFederatedUpstreamYamlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FederatedUpstreamRef *v11.ObjectRef `protobuf:"bytes,1,opt,name=federated_upstream_ref,json=federatedUpstreamRef,proto3" json:"federated_upstream_ref,omitempty"`
}

func (x *GetFederatedUpstreamYamlRequest) Reset() {
	*x = GetFederatedUpstreamYamlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFederatedUpstreamYamlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFederatedUpstreamYamlRequest) ProtoMessage() {}

func (x *GetFederatedUpstreamYamlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFederatedUpstreamYamlRequest.ProtoReflect.Descriptor instead.
func (*GetFederatedUpstreamYamlRequest) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{5}
}

func (x *GetFederatedUpstreamYamlRequest) GetFederatedUpstreamRef() *v11.ObjectRef {
	if x != nil {
		return x.FederatedUpstreamRef
	}
	return nil
}

type GetFederatedUpstreamYamlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YamlData *v1.ResourceYaml `protobuf:"bytes,1,opt,name=yaml_data,json=yamlData,proto3" json:"yaml_data,omitempty"`
}

func (x *GetFederatedUpstreamYamlResponse) Reset() {
	*x = GetFederatedUpstreamYamlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFederatedUpstreamYamlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFederatedUpstreamYamlResponse) ProtoMessage() {}

func (x *GetFederatedUpstreamYamlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFederatedUpstreamYamlResponse.ProtoReflect.Descriptor instead.
func (*GetFederatedUpstreamYamlResponse) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{6}
}

func (x *GetFederatedUpstreamYamlResponse) GetYamlData() *v1.ResourceYaml {
	if x != nil {
		return x.YamlData
	}
	return nil
}

type ListFederatedUpstreamGroupsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFederatedUpstreamGroupsRequest) Reset() {
	*x = ListFederatedUpstreamGroupsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFederatedUpstreamGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederatedUpstreamGroupsRequest) ProtoMessage() {}

func (x *ListFederatedUpstreamGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederatedUpstreamGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListFederatedUpstreamGroupsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{7}
}

type ListFederatedUpstreamGroupsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FederatedUpstreamGroups []*FederatedUpstreamGroup `protobuf:"bytes,1,rep,name=federated_upstream_groups,json=federatedUpstreamGroups,proto3" json:"federated_upstream_groups,omitempty"`
}

func (x *ListFederatedUpstreamGroupsResponse) Reset() {
	*x = ListFederatedUpstreamGroupsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFederatedUpstreamGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederatedUpstreamGroupsResponse) ProtoMessage() {}

func (x *ListFederatedUpstreamGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederatedUpstreamGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListFederatedUpstreamGroupsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{8}
}

func (x *ListFederatedUpstreamGroupsResponse) GetFederatedUpstreamGroups() []*FederatedUpstreamGroup {
	if x != nil {
		return x.FederatedUpstreamGroups
	}
	return nil
}

type GetFederatedUpstreamGroupYamlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FederatedUpstreamGroupRef *v11.ObjectRef `protobuf:"bytes,1,opt,name=federated_upstream_group_ref,json=federatedUpstreamGroupRef,proto3" json:"federated_upstream_group_ref,omitempty"`
}

func (x *GetFederatedUpstreamGroupYamlRequest) Reset() {
	*x = GetFederatedUpstreamGroupYamlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFederatedUpstreamGroupYamlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFederatedUpstreamGroupYamlRequest) ProtoMessage() {}

func (x *GetFederatedUpstreamGroupYamlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFederatedUpstreamGroupYamlRequest.ProtoReflect.Descriptor instead.
func (*GetFederatedUpstreamGroupYamlRequest) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{9}
}

func (x *GetFederatedUpstreamGroupYamlRequest) GetFederatedUpstreamGroupRef() *v11.ObjectRef {
	if x != nil {
		return x.FederatedUpstreamGroupRef
	}
	return nil
}

type GetFederatedUpstreamGroupYamlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YamlData *v1.ResourceYaml `protobuf:"bytes,1,opt,name=yaml_data,json=yamlData,proto3" json:"yaml_data,omitempty"`
}

func (x *GetFederatedUpstreamGroupYamlResponse) Reset() {
	*x = GetFederatedUpstreamGroupYamlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFederatedUpstreamGroupYamlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFederatedUpstreamGroupYamlResponse) ProtoMessage() {}

func (x *GetFederatedUpstreamGroupYamlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFederatedUpstreamGroupYamlResponse.ProtoReflect.Descriptor instead.
func (*GetFederatedUpstreamGroupYamlResponse) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{10}
}

func (x *GetFederatedUpstreamGroupYamlResponse) GetYamlData() *v1.ResourceYaml {
	if x != nil {
		return x.YamlData
	}
	return nil
}

type ListFederatedSettingsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFederatedSettingsRequest) Reset() {
	*x = ListFederatedSettingsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFederatedSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederatedSettingsRequest) ProtoMessage() {}

func (x *ListFederatedSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederatedSettingsRequest.ProtoReflect.Descriptor instead.
func (*ListFederatedSettingsRequest) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{11}
}

type ListFederatedSettingsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FederatedSettings []*FederatedSettings `protobuf:"bytes,1,rep,name=federated_settings,json=federatedSettings,proto3" json:"federated_settings,omitempty"`
}

func (x *ListFederatedSettingsResponse) Reset() {
	*x = ListFederatedSettingsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFederatedSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFederatedSettingsResponse) ProtoMessage() {}

func (x *ListFederatedSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFederatedSettingsResponse.ProtoReflect.Descriptor instead.
func (*ListFederatedSettingsResponse) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{12}
}

func (x *ListFederatedSettingsResponse) GetFederatedSettings() []*FederatedSettings {
	if x != nil {
		return x.FederatedSettings
	}
	return nil
}

type GetFederatedSettingsYamlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FederatedSettingsRef *v11.ObjectRef `protobuf:"bytes,1,opt,name=federated_settings_ref,json=federatedSettingsRef,proto3" json:"federated_settings_ref,omitempty"`
}

func (x *GetFederatedSettingsYamlRequest) Reset() {
	*x = GetFederatedSettingsYamlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFederatedSettingsYamlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFederatedSettingsYamlRequest) ProtoMessage() {}

func (x *GetFederatedSettingsYamlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFederatedSettingsYamlRequest.ProtoReflect.Descriptor instead.
func (*GetFederatedSettingsYamlRequest) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{13}
}

func (x *GetFederatedSettingsYamlRequest) GetFederatedSettingsRef() *v11.ObjectRef {
	if x != nil {
		return x.FederatedSettingsRef
	}
	return nil
}

type GetFederatedSettingsYamlResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YamlData *v1.ResourceYaml `protobuf:"bytes,1,opt,name=yaml_data,json=yamlData,proto3" json:"yaml_data,omitempty"`
}

func (x *GetFederatedSettingsYamlResponse) Reset() {
	*x = GetFederatedSettingsYamlResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFederatedSettingsYamlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFederatedSettingsYamlResponse) ProtoMessage() {}

func (x *GetFederatedSettingsYamlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFederatedSettingsYamlResponse.ProtoReflect.Descriptor instead.
func (*GetFederatedSettingsYamlResponse) Descriptor() ([]byte, []int) {
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP(), []int{14}
}

func (x *GetFederatedSettingsYamlResponse) GetYamlData() *v1.ResourceYaml {
	if x != nil {
		return x.YamlData
	}
	return nil
}

var File_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto protoreflect.FileDescriptor

var file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDesc = []byte{
	0x0a, 0x61, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c,
	0x6f, 0x2d, 0x69, 0x6f, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70,
	0x63, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x67,
	0x6c, 0x6f, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c,
	0x6f, 0x2e, 0x69, 0x6f, 0x1a, 0x12, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x65,
	0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x51, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x2d, 0x69, 0x6f, 0x2f, 0x73, 0x6f, 0x6c,
	0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65,
	0x63, 0x74, 0x73, 0x2f, 0x67, 0x6c, 0x6f, 0x6f, 0x2d, 0x66, 0x65, 0x64, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x66, 0x65, 0x64, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x70, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x57, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x2d, 0x69, 0x6f, 0x2f,
	0x73, 0x6f, 0x6c, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x67, 0x6c, 0x6f, 0x6f, 0x2d, 0x66, 0x65, 0x64, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x66, 0x65, 0x64, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2f, 0x76, 0x31, 0x2f,
	0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x51, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x2d, 0x69, 0x6f, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x2d, 0x70, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f,
	0x67, 0x6c, 0x6f, 0x6f, 0x2d, 0x66, 0x65, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x65, 0x64,
	0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x2d, 0x69, 0x6f, 0x2f, 0x73, 0x6b, 0x76, 0x32,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x55, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x2d, 0x69, 0x6f, 0x2f, 0x73, 0x6f, 0x6c, 0x6f,
	0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63,
	0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd2,
	0x01, 0x0a, 0x11, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x3d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x64, 0x67,
	0x65, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2e, 0x73, 0x6f, 0x6c,
	0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63,
	0x12, 0x41, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x29, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2e, 0x73, 0x6f, 0x6c, 0x6f,
	0x2e, 0x69, 0x6f, 0x2e, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0xe1, 0x01, 0x0a, 0x16, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x3d,
	0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x67, 0x6c, 0x6f, 0x6f,
	0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x40, 0x0a,
	0x04, 0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x66, 0x65,
	0x64, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x46,
	0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12,
	0x46, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2e, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e,
	0x69, 0x6f, 0x2e, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xd2, 0x01, 0x0a, 0x11, 0x46, 0x65, 0x64, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x3d, 0x0a,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2e,
	0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x3b, 0x0a, 0x04,
	0x73, 0x70, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x66, 0x65, 0x64,
	0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x46, 0x65,
	0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x04, 0x73, 0x70, 0x65, 0x63, 0x12, 0x41, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x66, 0x65, 0x64, 0x2e,
	0x67, 0x6c, 0x6f, 0x6f, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x46, 0x65, 0x64,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1f, 0x0a, 0x1d,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x75, 0x0a,
	0x1e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x53, 0x0a, 0x13, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x70, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66,
	0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x46,
	0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x52, 0x12, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x73, 0x22, 0x75, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x59, 0x61, 0x6d, 0x6c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x52, 0x0a, 0x16, 0x66, 0x65, 0x64, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x72, 0x65,
	0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73,
	0x6b, 0x76, 0x32, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x66, 0x52, 0x14, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x66, 0x22, 0x64, 0x0a, 0x20, 0x47,
	0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x09, 0x79, 0x61, 0x6d, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x67, 0x6c,
	0x6f, 0x6f, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x08, 0x79, 0x61, 0x6d, 0x6c, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x24, 0x0a, 0x22, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x8a, 0x01, 0x0a, 0x23, 0x4c, 0x69, 0x73, 0x74,
	0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x63, 0x0a, 0x19, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x70, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x27, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c,
	0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x17, 0x66, 0x65, 0x64,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x22, 0x85, 0x01, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x5d, 0x0a,
	0x1c, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x75, 0x70, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x6b, 0x76, 0x32, 0x2e,
	0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x66, 0x52, 0x19, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x66, 0x22, 0x69, 0x0a, 0x25,
	0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x79, 0x61, 0x6d, 0x6c, 0x5f, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x65,
	0x64, 0x67, 0x65, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x08, 0x79,
	0x61, 0x6d, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22, 0x1e, 0x0a, 0x1c, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x72, 0x0a, 0x1d, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x51, 0x0a, 0x12, 0x66, 0x65, 0x64, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73,
	0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x11, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x75, 0x0a, 0x1f, 0x47,
	0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x52,
	0x0a, 0x16, 0x66, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x73, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x73, 0x6b, 0x76, 0x32, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e,
	0x69, 0x6f, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x66, 0x52, 0x14, 0x66, 0x65,
	0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52,
	0x65, 0x66, 0x22, 0x64, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x79, 0x61, 0x6d, 0x6c, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x65, 0x64, 0x67, 0x65, 0x2e, 0x67, 0x6c, 0x6f, 0x6f, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69,
	0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x08,
	0x79, 0x61, 0x6d, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x32, 0xb9, 0x06, 0x0a, 0x18, 0x46, 0x65, 0x64,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x47, 0x6c, 0x6f, 0x6f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x41, 0x70, 0x69, 0x12, 0x7b, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x64,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x12,
	0x2e, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69,
	0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55,
	0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2f, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69,
	0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55,
	0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x81, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x59, 0x61, 0x6d, 0x6c, 0x12,
	0x30, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70,
	0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x31, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f,
	0x2e, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x8a, 0x01, 0x0a, 0x1b, 0x4c, 0x69, 0x73, 0x74, 0x46,
	0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x12, 0x33, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x64,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x34, 0x2e, 0x66, 0x65,
	0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x90, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x59, 0x61, 0x6d, 0x6c, 0x12, 0x35, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x66,
	0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x55, 0x70, 0x73, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x78, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65,
	0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x2d, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69,
	0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e,
	0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x81, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x59, 0x61, 0x6d, 0x6c, 0x12, 0x30, 0x2e,
	0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x73, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x31, 0x2e, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x73, 0x6f, 0x6c, 0x6f, 0x2e, 0x69,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x65, 0x64, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x53, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x59, 0x61, 0x6d, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x50, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x2d, 0x69, 0x6f, 0x2f, 0x73, 0x6f, 0x6c, 0x6f, 0x2d,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74,
	0x73, 0x2f, 0x61, 0x70, 0x69, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x66, 0x65, 0x64, 0x2e, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0xc0, 0xf5,
	0x04, 0x01, 0xb8, 0xf5, 0x04, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescOnce sync.Once
	file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescData = file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDesc
)

func file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescGZIP() []byte {
	file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescOnce.Do(func() {
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescData)
	})
	return file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDescData
}

var file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_goTypes = []interface{}{
	(*FederatedUpstream)(nil),                     // 0: fed.rpc.solo.io.FederatedUpstream
	(*FederatedUpstreamGroup)(nil),                // 1: fed.rpc.solo.io.FederatedUpstreamGroup
	(*FederatedSettings)(nil),                     // 2: fed.rpc.solo.io.FederatedSettings
	(*ListFederatedUpstreamsRequest)(nil),         // 3: fed.rpc.solo.io.ListFederatedUpstreamsRequest
	(*ListFederatedUpstreamsResponse)(nil),        // 4: fed.rpc.solo.io.ListFederatedUpstreamsResponse
	(*GetFederatedUpstreamYamlRequest)(nil),       // 5: fed.rpc.solo.io.GetFederatedUpstreamYamlRequest
	(*GetFederatedUpstreamYamlResponse)(nil),      // 6: fed.rpc.solo.io.GetFederatedUpstreamYamlResponse
	(*ListFederatedUpstreamGroupsRequest)(nil),    // 7: fed.rpc.solo.io.ListFederatedUpstreamGroupsRequest
	(*ListFederatedUpstreamGroupsResponse)(nil),   // 8: fed.rpc.solo.io.ListFederatedUpstreamGroupsResponse
	(*GetFederatedUpstreamGroupYamlRequest)(nil),  // 9: fed.rpc.solo.io.GetFederatedUpstreamGroupYamlRequest
	(*GetFederatedUpstreamGroupYamlResponse)(nil), // 10: fed.rpc.solo.io.GetFederatedUpstreamGroupYamlResponse
	(*ListFederatedSettingsRequest)(nil),          // 11: fed.rpc.solo.io.ListFederatedSettingsRequest
	(*ListFederatedSettingsResponse)(nil),         // 12: fed.rpc.solo.io.ListFederatedSettingsResponse
	(*GetFederatedSettingsYamlRequest)(nil),       // 13: fed.rpc.solo.io.GetFederatedSettingsYamlRequest
	(*GetFederatedSettingsYamlResponse)(nil),      // 14: fed.rpc.solo.io.GetFederatedSettingsYamlResponse
	(*v1.ObjectMeta)(nil),                         // 15: rpc.edge.gloo.solo.io.ObjectMeta
	(*types.FederatedUpstreamSpec)(nil),           // 16: fed.gloo.solo.io.FederatedUpstreamSpec
	(*types.FederatedUpstreamStatus)(nil),         // 17: fed.gloo.solo.io.FederatedUpstreamStatus
	(*types.FederatedUpstreamGroupSpec)(nil),      // 18: fed.gloo.solo.io.FederatedUpstreamGroupSpec
	(*types.FederatedUpstreamGroupStatus)(nil),    // 19: fed.gloo.solo.io.FederatedUpstreamGroupStatus
	(*types.FederatedSettingsSpec)(nil),           // 20: fed.gloo.solo.io.FederatedSettingsSpec
	(*types.FederatedSettingsStatus)(nil),         // 21: fed.gloo.solo.io.FederatedSettingsStatus
	(*v11.ObjectRef)(nil),                         // 22: core.skv2.solo.io.ObjectRef
	(*v1.ResourceYaml)(nil),                       // 23: rpc.edge.gloo.solo.io.ResourceYaml
}
var file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_depIdxs = []int32{
	15, // 0: fed.rpc.solo.io.FederatedUpstream.metadata:type_name -> rpc.edge.gloo.solo.io.ObjectMeta
	16, // 1: fed.rpc.solo.io.FederatedUpstream.spec:type_name -> fed.gloo.solo.io.FederatedUpstreamSpec
	17, // 2: fed.rpc.solo.io.FederatedUpstream.status:type_name -> fed.gloo.solo.io.FederatedUpstreamStatus
	15, // 3: fed.rpc.solo.io.FederatedUpstreamGroup.metadata:type_name -> rpc.edge.gloo.solo.io.ObjectMeta
	18, // 4: fed.rpc.solo.io.FederatedUpstreamGroup.spec:type_name -> fed.gloo.solo.io.FederatedUpstreamGroupSpec
	19, // 5: fed.rpc.solo.io.FederatedUpstreamGroup.status:type_name -> fed.gloo.solo.io.FederatedUpstreamGroupStatus
	15, // 6: fed.rpc.solo.io.FederatedSettings.metadata:type_name -> rpc.edge.gloo.solo.io.ObjectMeta
	20, // 7: fed.rpc.solo.io.FederatedSettings.spec:type_name -> fed.gloo.solo.io.FederatedSettingsSpec
	21, // 8: fed.rpc.solo.io.FederatedSettings.status:type_name -> fed.gloo.solo.io.FederatedSettingsStatus
	0,  // 9: fed.rpc.solo.io.ListFederatedUpstreamsResponse.federated_upstreams:type_name -> fed.rpc.solo.io.FederatedUpstream
	22, // 10: fed.rpc.solo.io.GetFederatedUpstreamYamlRequest.federated_upstream_ref:type_name -> core.skv2.solo.io.ObjectRef
	23, // 11: fed.rpc.solo.io.GetFederatedUpstreamYamlResponse.yaml_data:type_name -> rpc.edge.gloo.solo.io.ResourceYaml
	1,  // 12: fed.rpc.solo.io.ListFederatedUpstreamGroupsResponse.federated_upstream_groups:type_name -> fed.rpc.solo.io.FederatedUpstreamGroup
	22, // 13: fed.rpc.solo.io.GetFederatedUpstreamGroupYamlRequest.federated_upstream_group_ref:type_name -> core.skv2.solo.io.ObjectRef
	23, // 14: fed.rpc.solo.io.GetFederatedUpstreamGroupYamlResponse.yaml_data:type_name -> rpc.edge.gloo.solo.io.ResourceYaml
	2,  // 15: fed.rpc.solo.io.ListFederatedSettingsResponse.federated_settings:type_name -> fed.rpc.solo.io.FederatedSettings
	22, // 16: fed.rpc.solo.io.GetFederatedSettingsYamlRequest.federated_settings_ref:type_name -> core.skv2.solo.io.ObjectRef
	23, // 17: fed.rpc.solo.io.GetFederatedSettingsYamlResponse.yaml_data:type_name -> rpc.edge.gloo.solo.io.ResourceYaml
	3,  // 18: fed.rpc.solo.io.FederatedGlooResourceApi.ListFederatedUpstreams:input_type -> fed.rpc.solo.io.ListFederatedUpstreamsRequest
	5,  // 19: fed.rpc.solo.io.FederatedGlooResourceApi.GetFederatedUpstreamYaml:input_type -> fed.rpc.solo.io.GetFederatedUpstreamYamlRequest
	7,  // 20: fed.rpc.solo.io.FederatedGlooResourceApi.ListFederatedUpstreamGroups:input_type -> fed.rpc.solo.io.ListFederatedUpstreamGroupsRequest
	9,  // 21: fed.rpc.solo.io.FederatedGlooResourceApi.GetFederatedUpstreamGroupYaml:input_type -> fed.rpc.solo.io.GetFederatedUpstreamGroupYamlRequest
	11, // 22: fed.rpc.solo.io.FederatedGlooResourceApi.ListFederatedSettings:input_type -> fed.rpc.solo.io.ListFederatedSettingsRequest
	13, // 23: fed.rpc.solo.io.FederatedGlooResourceApi.GetFederatedSettingsYaml:input_type -> fed.rpc.solo.io.GetFederatedSettingsYamlRequest
	4,  // 24: fed.rpc.solo.io.FederatedGlooResourceApi.ListFederatedUpstreams:output_type -> fed.rpc.solo.io.ListFederatedUpstreamsResponse
	6,  // 25: fed.rpc.solo.io.FederatedGlooResourceApi.GetFederatedUpstreamYaml:output_type -> fed.rpc.solo.io.GetFederatedUpstreamYamlResponse
	8,  // 26: fed.rpc.solo.io.FederatedGlooResourceApi.ListFederatedUpstreamGroups:output_type -> fed.rpc.solo.io.ListFederatedUpstreamGroupsResponse
	10, // 27: fed.rpc.solo.io.FederatedGlooResourceApi.GetFederatedUpstreamGroupYaml:output_type -> fed.rpc.solo.io.GetFederatedUpstreamGroupYamlResponse
	12, // 28: fed.rpc.solo.io.FederatedGlooResourceApi.ListFederatedSettings:output_type -> fed.rpc.solo.io.ListFederatedSettingsResponse
	14, // 29: fed.rpc.solo.io.FederatedGlooResourceApi.GetFederatedSettingsYaml:output_type -> fed.rpc.solo.io.GetFederatedSettingsYamlResponse
	24, // [24:30] is the sub-list for method output_type
	18, // [18:24] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() {
	file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_init()
}
func file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_init() {
	if File_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FederatedUpstream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FederatedUpstreamGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FederatedSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFederatedUpstreamsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFederatedUpstreamsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFederatedUpstreamYamlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFederatedUpstreamYamlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFederatedUpstreamGroupsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFederatedUpstreamGroupsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFederatedUpstreamGroupYamlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFederatedUpstreamGroupYamlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFederatedSettingsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFederatedSettingsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFederatedSettingsYamlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFederatedSettingsYamlResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_goTypes,
		DependencyIndexes: file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_depIdxs,
		MessageInfos:      file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_msgTypes,
	}.Build()
	File_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto = out.File
	file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_rawDesc = nil
	file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_goTypes = nil
	file_github_com_solo_io_solo_projects_projects_apiserver_api_fed_rpc_v1_federated_gloo_resources_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FederatedGlooResourceApiClient is the client API for FederatedGlooResourceApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FederatedGlooResourceApiClient interface {
	ListFederatedUpstreams(ctx context.Context, in *ListFederatedUpstreamsRequest, opts ...grpc.CallOption) (*ListFederatedUpstreamsResponse, error)
	GetFederatedUpstreamYaml(ctx context.Context, in *GetFederatedUpstreamYamlRequest, opts ...grpc.CallOption) (*GetFederatedUpstreamYamlResponse, error)
	ListFederatedUpstreamGroups(ctx context.Context, in *ListFederatedUpstreamGroupsRequest, opts ...grpc.CallOption) (*ListFederatedUpstreamGroupsResponse, error)
	GetFederatedUpstreamGroupYaml(ctx context.Context, in *GetFederatedUpstreamGroupYamlRequest, opts ...grpc.CallOption) (*GetFederatedUpstreamGroupYamlResponse, error)
	ListFederatedSettings(ctx context.Context, in *ListFederatedSettingsRequest, opts ...grpc.CallOption) (*ListFederatedSettingsResponse, error)
	GetFederatedSettingsYaml(ctx context.Context, in *GetFederatedSettingsYamlRequest, opts ...grpc.CallOption) (*GetFederatedSettingsYamlResponse, error)
}

type federatedGlooResourceApiClient struct {
	cc grpc.ClientConnInterface
}

func NewFederatedGlooResourceApiClient(cc grpc.ClientConnInterface) FederatedGlooResourceApiClient {
	return &federatedGlooResourceApiClient{cc}
}

func (c *federatedGlooResourceApiClient) ListFederatedUpstreams(ctx context.Context, in *ListFederatedUpstreamsRequest, opts ...grpc.CallOption) (*ListFederatedUpstreamsResponse, error) {
	out := new(ListFederatedUpstreamsResponse)
	err := c.cc.Invoke(ctx, "/fed.rpc.solo.io.FederatedGlooResourceApi/ListFederatedUpstreams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedGlooResourceApiClient) GetFederatedUpstreamYaml(ctx context.Context, in *GetFederatedUpstreamYamlRequest, opts ...grpc.CallOption) (*GetFederatedUpstreamYamlResponse, error) {
	out := new(GetFederatedUpstreamYamlResponse)
	err := c.cc.Invoke(ctx, "/fed.rpc.solo.io.FederatedGlooResourceApi/GetFederatedUpstreamYaml", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedGlooResourceApiClient) ListFederatedUpstreamGroups(ctx context.Context, in *ListFederatedUpstreamGroupsRequest, opts ...grpc.CallOption) (*ListFederatedUpstreamGroupsResponse, error) {
	out := new(ListFederatedUpstreamGroupsResponse)
	err := c.cc.Invoke(ctx, "/fed.rpc.solo.io.FederatedGlooResourceApi/ListFederatedUpstreamGroups", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedGlooResourceApiClient) GetFederatedUpstreamGroupYaml(ctx context.Context, in *GetFederatedUpstreamGroupYamlRequest, opts ...grpc.CallOption) (*GetFederatedUpstreamGroupYamlResponse, error) {
	out := new(GetFederatedUpstreamGroupYamlResponse)
	err := c.cc.Invoke(ctx, "/fed.rpc.solo.io.FederatedGlooResourceApi/GetFederatedUpstreamGroupYaml", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedGlooResourceApiClient) ListFederatedSettings(ctx context.Context, in *ListFederatedSettingsRequest, opts ...grpc.CallOption) (*ListFederatedSettingsResponse, error) {
	out := new(ListFederatedSettingsResponse)
	err := c.cc.Invoke(ctx, "/fed.rpc.solo.io.FederatedGlooResourceApi/ListFederatedSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *federatedGlooResourceApiClient) GetFederatedSettingsYaml(ctx context.Context, in *GetFederatedSettingsYamlRequest, opts ...grpc.CallOption) (*GetFederatedSettingsYamlResponse, error) {
	out := new(GetFederatedSettingsYamlResponse)
	err := c.cc.Invoke(ctx, "/fed.rpc.solo.io.FederatedGlooResourceApi/GetFederatedSettingsYaml", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FederatedGlooResourceApiServer is the server API for FederatedGlooResourceApi service.
type FederatedGlooResourceApiServer interface {
	ListFederatedUpstreams(context.Context, *ListFederatedUpstreamsRequest) (*ListFederatedUpstreamsResponse, error)
	GetFederatedUpstreamYaml(context.Context, *GetFederatedUpstreamYamlRequest) (*GetFederatedUpstreamYamlResponse, error)
	ListFederatedUpstreamGroups(context.Context, *ListFederatedUpstreamGroupsRequest) (*ListFederatedUpstreamGroupsResponse, error)
	GetFederatedUpstreamGroupYaml(context.Context, *GetFederatedUpstreamGroupYamlRequest) (*GetFederatedUpstreamGroupYamlResponse, error)
	ListFederatedSettings(context.Context, *ListFederatedSettingsRequest) (*ListFederatedSettingsResponse, error)
	GetFederatedSettingsYaml(context.Context, *GetFederatedSettingsYamlRequest) (*GetFederatedSettingsYamlResponse, error)
}

// UnimplementedFederatedGlooResourceApiServer can be embedded to have forward compatible implementations.
type UnimplementedFederatedGlooResourceApiServer struct {
}

func (*UnimplementedFederatedGlooResourceApiServer) ListFederatedUpstreams(context.Context, *ListFederatedUpstreamsRequest) (*ListFederatedUpstreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFederatedUpstreams not implemented")
}
func (*UnimplementedFederatedGlooResourceApiServer) GetFederatedUpstreamYaml(context.Context, *GetFederatedUpstreamYamlRequest) (*GetFederatedUpstreamYamlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFederatedUpstreamYaml not implemented")
}
func (*UnimplementedFederatedGlooResourceApiServer) ListFederatedUpstreamGroups(context.Context, *ListFederatedUpstreamGroupsRequest) (*ListFederatedUpstreamGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFederatedUpstreamGroups not implemented")
}
func (*UnimplementedFederatedGlooResourceApiServer) GetFederatedUpstreamGroupYaml(context.Context, *GetFederatedUpstreamGroupYamlRequest) (*GetFederatedUpstreamGroupYamlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFederatedUpstreamGroupYaml not implemented")
}
func (*UnimplementedFederatedGlooResourceApiServer) ListFederatedSettings(context.Context, *ListFederatedSettingsRequest) (*ListFederatedSettingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFederatedSettings not implemented")
}
func (*UnimplementedFederatedGlooResourceApiServer) GetFederatedSettingsYaml(context.Context, *GetFederatedSettingsYamlRequest) (*GetFederatedSettingsYamlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFederatedSettingsYaml not implemented")
}

func RegisterFederatedGlooResourceApiServer(s *grpc.Server, srv FederatedGlooResourceApiServer) {
	s.RegisterService(&_FederatedGlooResourceApi_serviceDesc, srv)
}

func _FederatedGlooResourceApi_ListFederatedUpstreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFederatedUpstreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedGlooResourceApiServer).ListFederatedUpstreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fed.rpc.solo.io.FederatedGlooResourceApi/ListFederatedUpstreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedGlooResourceApiServer).ListFederatedUpstreams(ctx, req.(*ListFederatedUpstreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedGlooResourceApi_GetFederatedUpstreamYaml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFederatedUpstreamYamlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedGlooResourceApiServer).GetFederatedUpstreamYaml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fed.rpc.solo.io.FederatedGlooResourceApi/GetFederatedUpstreamYaml",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedGlooResourceApiServer).GetFederatedUpstreamYaml(ctx, req.(*GetFederatedUpstreamYamlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedGlooResourceApi_ListFederatedUpstreamGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFederatedUpstreamGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedGlooResourceApiServer).ListFederatedUpstreamGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fed.rpc.solo.io.FederatedGlooResourceApi/ListFederatedUpstreamGroups",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedGlooResourceApiServer).ListFederatedUpstreamGroups(ctx, req.(*ListFederatedUpstreamGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedGlooResourceApi_GetFederatedUpstreamGroupYaml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFederatedUpstreamGroupYamlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedGlooResourceApiServer).GetFederatedUpstreamGroupYaml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fed.rpc.solo.io.FederatedGlooResourceApi/GetFederatedUpstreamGroupYaml",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedGlooResourceApiServer).GetFederatedUpstreamGroupYaml(ctx, req.(*GetFederatedUpstreamGroupYamlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedGlooResourceApi_ListFederatedSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFederatedSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedGlooResourceApiServer).ListFederatedSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fed.rpc.solo.io.FederatedGlooResourceApi/ListFederatedSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedGlooResourceApiServer).ListFederatedSettings(ctx, req.(*ListFederatedSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FederatedGlooResourceApi_GetFederatedSettingsYaml_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFederatedSettingsYamlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FederatedGlooResourceApiServer).GetFederatedSettingsYaml(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fed.rpc.solo.io.FederatedGlooResourceApi/GetFederatedSettingsYaml",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FederatedGlooResourceApiServer).GetFederatedSettingsYaml(ctx, req.(*GetFederatedSettingsYamlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FederatedGlooResourceApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fed.rpc.solo.io.FederatedGlooResourceApi",
	HandlerType: (*FederatedGlooResourceApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFederatedUpstreams",
			Handler:    _FederatedGlooResourceApi_ListFederatedUpstreams_Handler,
		},
		{
			MethodName: "GetFederatedUpstreamYaml",
			Handler:    _FederatedGlooResourceApi_GetFederatedUpstreamYaml_Handler,
		},
		{
			MethodName: "ListFederatedUpstreamGroups",
			Handler:    _FederatedGlooResourceApi_ListFederatedUpstreamGroups_Handler,
		},
		{
			MethodName: "GetFederatedUpstreamGroupYaml",
			Handler:    _FederatedGlooResourceApi_GetFederatedUpstreamGroupYaml_Handler,
		},
		{
			MethodName: "ListFederatedSettings",
			Handler:    _FederatedGlooResourceApi_ListFederatedSettings_Handler,
		},
		{
			MethodName: "GetFederatedSettingsYaml",
			Handler:    _FederatedGlooResourceApi_GetFederatedSettingsYaml_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/solo-io/solo-projects/projects/apiserver/api/fed.rpc/v1/federated_gloo_resources.proto",
}
