name: Bug Report
description: Create a report to help us improve
labels: ["Type: Bug"]
body:
  - type: dropdown
    id: version
    attributes:
      label: Gloo Edge Version
      description: What version of Gloo Edge are you using?
      options:
        - 1.15.x (beta)
        - 1.14.x (latest stable)
        - 1.13.x
        - 1.12.x
        - 1.11.x
    validations:
      required: true
  - type: dropdown
    id: kube-version
    attributes:
      label: Kubernetes Version
      description: What version of Kubernetes are you using with Gloo Edge?
      options:
        - 1.27.x
        - 1.26.x
        - 1.25.x
        - 1.24.x
        - 1.23.x
        - 1.22.x 
        - 1.21.x
        - 1.20.x
        - 1.19.x
        - 1.18.x
        - 1.17.x 
        - 1.16.x
        - 1.15.x
        - 1.14.x
        - 1.13.x
        - 1.12.x
  - type: textarea
    id: describe-bug
    attributes:
      label: Describe the bug
      placeholder: Add a clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to reproduce the bug
      placeholder: |
        1. kube apply '...'
        2. curl '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      placeholder: When I performed x, I expected y to happen
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: |
        Additional information specific to this issue
