name: Feature Request
description: Suggest an idea for this project
labels: ["Type: Enhancement"]
body:
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Gloo Edge are you using?
      options:
        - 1.15.x (beta)
        - 1.14.x (latest stable)
        - 1.13.x
        - 1.12.x
        - 1.11.x
  - type: textarea
    id: problem-details
    attributes:
      label: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: solution-details
    attributes:
      label: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives-details
    attributes:
      label: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Add any other context or screenshots about the feature request here.
