// Code generated by MockGen. DO NOT EDIT.
// Source: ./projects/vcs/pkg/api/v1/change_set_client.sk.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	clients "github.com/solo-io/solo-kit/pkg/api/v1/clients"
	v1 "github.com/solo-io/solo-projects/projects/vcs/pkg/api/v1"
)

// MockChangeSetWatcher is a mock of ChangeSetWatcher interface
type MockChangeSetWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockChangeSetWatcherMockRecorder
}

// MockChangeSetWatcherMockRecorder is the mock recorder for MockChangeSetWatcher
type MockChangeSetWatcherMockRecorder struct {
	mock *MockChangeSetWatcher
}

// NewMockChangeSetWatcher creates a new mock instance
func NewMockChangeSetWatcher(ctrl *gomock.Controller) *MockChangeSetWatcher {
	mock := &MockChangeSetWatcher{ctrl: ctrl}
	mock.recorder = &MockChangeSetWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChangeSetWatcher) EXPECT() *MockChangeSetWatcherMockRecorder {
	return m.recorder
}

// Watch mocks base method
func (m *MockChangeSetWatcher) Watch(namespace string, opts clients.WatchOpts) (<-chan v1.ChangeSetList, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", namespace, opts)
	ret0, _ := ret[0].(<-chan v1.ChangeSetList)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch
func (mr *MockChangeSetWatcherMockRecorder) Watch(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockChangeSetWatcher)(nil).Watch), namespace, opts)
}

// MockChangeSetClient is a mock of ChangeSetClient interface
type MockChangeSetClient struct {
	ctrl     *gomock.Controller
	recorder *MockChangeSetClientMockRecorder
}

// MockChangeSetClientMockRecorder is the mock recorder for MockChangeSetClient
type MockChangeSetClientMockRecorder struct {
	mock *MockChangeSetClient
}

// NewMockChangeSetClient creates a new mock instance
func NewMockChangeSetClient(ctrl *gomock.Controller) *MockChangeSetClient {
	mock := &MockChangeSetClient{ctrl: ctrl}
	mock.recorder = &MockChangeSetClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChangeSetClient) EXPECT() *MockChangeSetClientMockRecorder {
	return m.recorder
}

// BaseClient mocks base method
func (m *MockChangeSetClient) BaseClient() clients.ResourceClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseClient")
	ret0, _ := ret[0].(clients.ResourceClient)
	return ret0
}

// BaseClient indicates an expected call of BaseClient
func (mr *MockChangeSetClientMockRecorder) BaseClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseClient", reflect.TypeOf((*MockChangeSetClient)(nil).BaseClient))
}

// Register mocks base method
func (m *MockChangeSetClient) Register() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register")
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register
func (mr *MockChangeSetClientMockRecorder) Register() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockChangeSetClient)(nil).Register))
}

// Read mocks base method
func (m *MockChangeSetClient) Read(namespace, name string, opts clients.ReadOpts) (*v1.ChangeSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", namespace, name, opts)
	ret0, _ := ret[0].(*v1.ChangeSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockChangeSetClientMockRecorder) Read(namespace, name, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockChangeSetClient)(nil).Read), namespace, name, opts)
}

// Write mocks base method
func (m *MockChangeSetClient) Write(resource *v1.ChangeSet, opts clients.WriteOpts) (*v1.ChangeSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", resource, opts)
	ret0, _ := ret[0].(*v1.ChangeSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write
func (mr *MockChangeSetClientMockRecorder) Write(resource, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockChangeSetClient)(nil).Write), resource, opts)
}

// Delete mocks base method
func (m *MockChangeSetClient) Delete(namespace, name string, opts clients.DeleteOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", namespace, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockChangeSetClientMockRecorder) Delete(namespace, name, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockChangeSetClient)(nil).Delete), namespace, name, opts)
}

// List mocks base method
func (m *MockChangeSetClient) List(namespace string, opts clients.ListOpts) (v1.ChangeSetList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", namespace, opts)
	ret0, _ := ret[0].(v1.ChangeSetList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockChangeSetClientMockRecorder) List(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockChangeSetClient)(nil).List), namespace, opts)
}

// Watch mocks base method
func (m *MockChangeSetClient) Watch(namespace string, opts clients.WatchOpts) (<-chan v1.ChangeSetList, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", namespace, opts)
	ret0, _ := ret[0].(<-chan v1.ChangeSetList)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch
func (mr *MockChangeSetClientMockRecorder) Watch(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockChangeSetClient)(nil).Watch), namespace, opts)
}
