{
 "title": "Envoy Statistics",
 "tags": [ "gloo" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_total{app=\"gloo\"}[1m]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Percent Response Code per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"2\",app=\"gloo\"}[1m])) / sum(irate(envoy_http_downstream_rq_total{app=\"gloo\"}[1m]))",
     "legendFormat": "% 2xx"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\",app=\"gloo\"}[1m])) / sum(irate(envoy_http_downstream_rq_total{app=\"gloo\"}[1m]))",
     "legendFormat": "% 4xx"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\",app=\"gloo\"}[1m])) / sum(irate(envoy_http_downstream_rq_total{app=\"gloo\"}[1m]))",
     "legendFormat": "% 5xx"
    }
   ]
  },
  {
   "title": "Response Codes per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"2\",app=\"gloo\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"4\",app=\"gloo\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(envoy_http_downstream_rq_xx{envoy_response_code_class=\"5\",app=\"gloo\"}[1m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Average Request Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_sum{envoy_cluster_name=~\".*_gloo-system\",envoy_cluster_name!~\"kube*|gloo*\",app=\"gloo\"}[1m])) / sum(rate(envoy_cluster_upstream_rq_time_count{envoy_cluster_name=~\".*_gloo-system\",envoy_cluster_name!~\"kube*|gloo*\",app=\"gloo\"}[1m]))",
     "legendFormat": "average time to upstream"
    },
    {
     "expr": "sum(rate(envoy_http_downstream_rq_time_sum{envoy_http_conn_manager_prefix!~\"admin|prometheus|async-client\",app=\"gloo\"}[1m])) / sum(rate(envoy_http_downstream_rq_time_count{envoy_http_conn_manager_prefix!~\"(admin|prometheus|async-client)\",app=\"gloo\"}[1m]))",
     "legendFormat": "average time from downstream"
    }
   ]
  },
  {
   "title": "Upstream Request Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_cluster_upstream_rq_time_bucket{app=\"gloo\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{app=\"gloo\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{app=\"gloo\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Round Trip Time Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_http_downstream_rq_time_bucket{app=\"gloo\"}[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_http_downstream_rq_time_bucket{app=\"gloo\"}[1m])) by (le))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket{app=\"gloo\"}[1m])) by (le))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "External Auth Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_ext_authz_ok{app=\"gloo\"}[1m]))",
     "legendFormat": "OK"
    },
    {
     "expr": "sum(increase(envoy_cluster_ext_authz_denied{app=\"gloo\"}[1m]))",
     "legendFormat": "Denied"
    },
    {
     "expr": "sum(increase(envoy_cluster_ext_authz_error{app=\"gloo\"}[1m]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(increase(envoy_cluster_ext_authz_ok{app=\"gloo\"}[1m])) + sum(increase(envoy_cluster_ext_authz_denied{app=\"gloo\"}[1m])) + sum(increase(envoy_cluster_ext_authz_error{app=\"gloo\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}