{
 "title": "All Upstreams",
 "description": "Global overview of Gloo Edge Upstream CRs.",
 "tags": [
  "gloo",
  "dynamic"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "upstream",
    "label": "Upstream",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total{kubernetes_namespace=\"$namespace\"}, envoy_cluster_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# of HTTP requests (rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_total{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "upstream_rq_total"
    }
   ]
  },
  {
   "title": "HTTP response codes (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"2\",envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "2xx"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"3\",envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "3xx"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"4\",envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "4xx"
    },
    {
     "expr": "rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\",envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request Time Heatmap",
   "type": "heatmap",
   "description": "Displays the upstream request times calculated as buckets over 1 minute intervals.  The legend at the bottom left can be used as a guide to understand outliers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_bucket{ envoy_cluster_name=\"$upstream\", kubernetes_namespace=\"$namespace\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Request Time Quantiles",
   "type": "graph",
   "description": "This chart shows request time quantiles for the upstream in measurements of P99, P95 and P50.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_external_upstream_rq_time_bucket{ envoy_cluster_name=\"$upstream\", kubernetes_namespace=\"$namespace\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_external_upstream_rq_time_bucket{ envoy_cluster_name=\"$upstream\", kubernetes_namespace=\"$namespace\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_external_upstream_rq_time_bucket{ envoy_cluster_name=\"$upstream\", kubernetes_namespace=\"$namespace\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Connections, retries and circuit breaker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "Current active connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_upstream_cx_active{ envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "{{zone}} ({{host}})"
    }
   ]
  },
  {
   "title": "Circuit breaker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "circuit open" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_cx_open{envoy_cluster_name=\"$upstream\",app=\"gloo\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "circuit breaker status"
    }
   ]
  },
  {
   "title": "Retry counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_rq_retry{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "rq_retry"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_retry_backoff_ratelimited{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "rq_retry_backoff_ratelimited"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_retry_limit_exceeded{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "rq_retry_limit_exceeded"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_retry_overflow{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "rq_retry_overflow"
    },
    {
     "expr": "irate(envoy_cluster_upstream_rq_retry_success{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "rq_retry_success"
    }
   ]
  },
  {
   "title": "Retries limit reached (circuit breaker)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_circuit_breakers_default_rq_retry_open{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"} ",
     "legendFormat": "limit reached"
    }
   ]
  },
  {
   "title": "Health checks and Outlier detection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Status (health check)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_health_check_healthy{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "Healthy"
    }
   ]
  },
  {
   "title": "Outlier Detection counters",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_cluster_outlier_detection_ejections_consecutive_5xx{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "ejections_consecutive_5xx"
    },
    {
     "expr": "rate(envoy_cluster_outlier_detection_ejections_total{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "ejections_total"
    }
   ]
  },
  {
   "title": "Health Check failures (rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_health_check_failure{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m]))",
     "legendFormat": "number of failures"
    }
   ]
  },
  {
   "title": "Number of currently ejected hosts (outlier detection)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_cluster_outlier_detection_ejections_active{envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}",
     "legendFormat": "# of ejected hosts"
    }
   ]
  },
  { "title": "Network usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Upstream Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{ envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "IN"
    },
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{ envoy_cluster_name=\"$upstream\", app=\"gloo\", kubernetes_namespace=\"$namespace\"}[1m])",
     "legendFormat": "OUT"
    }
   ]
  }
 ]
}