{{- if .Values.glooFedApiserver.enable }}
{{- $glooFedApiserver := $.Values.glooFedApiserver }}
{{- $statsConfig := coalesce $glooFedApiserver.stats .Values.global.glooStats }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    gloo.solo.io/h2_service: "true"
  labels:
    app: gloo-fed
    gloo-fed: console
  name: gloo-fed-console
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: grpc
      port: {{ $glooFedApiserver.port }}
      protocol: TCP
    - name: static
      port: 8090
      protocol: TCP
    - name: healthcheck
      port: {{ $glooFedApiserver.healthCheckPort }}
      protocol: TCP
    {{- if $statsConfig.serviceMonitorEnabled }}
    - name: http-monitoring
      port: 9091
    {{- end }}
  selector:
    app: gloo-fed
    gloo-fed: console
  type: ClusterIP
{{- end }} {{/* .Values.glooFedApiserver.enable */}}
