{{- if .Values.enabled }}
{{- if .Values.rbac.create }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-fed-{{ .Release.Namespace }}
  labels:
    app: gloo-fed
rules:
- apiGroups:
  - gloo.solo.io
  resources:
  - settings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fed.solo.io
  resources:
  - glooinstances
  - failoverschemes
  verbs:
  - '*'
- apiGroups:
  - fed.solo.io
  resources:
  - glooinstances/status
  - failoverschemes/status
  verbs:
  - get
  - update
- apiGroups:
  - fed.gloo.solo.io
  resources:
  - federatedauthconfigs
  - federatedauthconfigs/status
  - federatedsettings
  - federatedsettings/status
  - federatedupstreams
  - federatedupstreams/status
  - federatedupstreamgroups
  - federatedupstreamgroups/status
  verbs:
  - '*'
- apiGroups:
  - fed.gateway.solo.io
  resources:
  - federatedvirtualservices
  - federatedvirtualservices/status
  - federatedgateways
  - federatedgateways/status
  - federatedmatchablehttpgateways
  - federatedmatchablehttpgateways/status
  - federatedroutetables
  - federatedroutetables/status
  verbs:
  - '*'
- apiGroups:
  - fed.enterprise.gloo.solo.io
  resources:
  - federatedauthconfigs
  - federatedauthconfigs/status
  verbs:
  - '*'
- apiGroups:
    - fed.ratelimit.solo.io
  resources:
    - federatedratelimitconfigs
    - federatedratelimitconfigs/status
  verbs:
    - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-fed-{{ .Release.Namespace }}
  labels:
    app: gloo-fed
subjects:
- kind: ServiceAccount
  name: gloo-fed
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gloo-fed-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-fed-console-{{ .Release.Namespace }}
  labels:
    app: gloo-fed
subjects:
- kind: ServiceAccount
  name: gloo-fed-console
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: gloo-fed-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }} {{/* .Values.enabled */}}
