{{- if .Values.enabled }}
{{- if $.Values.enableMultiClusterRbac }}

# Rbac manifests for gloo-fed-rbac-validating-webhook

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-validating-webhook-{{ .Release.Namespace }}
  labels:
    app: gloo-fed
    gloo-fed: rbac-validating-webhook
rules:
- apiGroups:
  - multicluster.solo.io
  resources:
  - multiclusterroles
  - multiclusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - update

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbac-validating-webhook-{{ .Release.Namespace }}
  labels:
    app: gloo-fed
    gloo-fed: rbac-validating-webhook
subjects:
- kind: ServiceAccount
  name: rbac-validating-webhook
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: rbac-validating-webhook-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io

{{ end }} {{/* if enableMultiClusterRbac */}}
{{- end }} {{/* .Values.enabled */}}