apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: foo-listenerset
spec:
  parentRef:
    name: example-gateway
    kind: Gateway
    group: gateway.networking.k8s.io
  listeners:
  - name: foo
    protocol: HTTP
    port: 8081
    allowedRoutes:
        namespaces:
          from: All
