kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# Do not use the default CNI as kindnet does not support custom network policies.
# Instead, cilium is installed as CNI as we need to test Kube API server unavailability in the kube2e tests
networking:
  disableDefaultCNI: true
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    metadata:
      name: config
  - |
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: InitConfiguration
    metadata:
      name: config