// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: upstream.proto

package v1 // import "github.com/solo-io/solo-projects/projects/gloo/pkg/api/v1"

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"

import bytes "bytes"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

//
// @solo-kit:resource.short_name=us
// @solo-kit:resource.plural_name=upstreams
// @solo-kit:resource.resource_groups=api.gloo.solo.io,discovery.gloo.solo.io,translator.supergloo.solo.io
//
// Upstreams represent destination for routing HTTP requests. Upstreams can be compared to
// [clusters](https://www.envoyproxy.io/docs/envoy/latest/api-v1/cluster_manager/cluster.html?highlight=cluster) in Envoy terminology.
// Each upstream in Gloo has a type. Supported types include `static`, `kubernetes`, `aws`, `consul`, and more.
// Each upstream type is handled by a corresponding Gloo plugin.
type Upstream struct {
	// Type-specific configuration. Examples include static, kubernetes, and aws.
	// The type-specific config for the upstream is called a spec.
	UpstreamSpec *UpstreamSpec `protobuf:"bytes,2,opt,name=upstream_spec,json=upstreamSpec" json:"upstream_spec,omitempty"`
	// Status indicates the validation status of the resource. Status is read-only by clients, and set by gloo during validation
	Status core.Status `protobuf:"bytes,6,opt,name=status" json:"status" testdiff:"ignore"`
	// Metadata contains the object metadata for this resource
	Metadata core.Metadata `protobuf:"bytes,7,opt,name=metadata" json:"metadata"`
	// Upstreams and their configuration can be automatically by Gloo Discovery
	// if this upstream is created or modified by Discovery, metadata about the operation will be placed here.
	DiscoveryMetadata    *DiscoveryMetadata `protobuf:"bytes,8,opt,name=discovery_metadata,json=discoveryMetadata" json:"discovery_metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Upstream) Reset()         { *m = Upstream{} }
func (m *Upstream) String() string { return proto.CompactTextString(m) }
func (*Upstream) ProtoMessage()    {}
func (*Upstream) Descriptor() ([]byte, []int) {
	return fileDescriptor_upstream_afa4af8e0d322f93, []int{0}
}
func (m *Upstream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Upstream.Unmarshal(m, b)
}
func (m *Upstream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Upstream.Marshal(b, m, deterministic)
}
func (dst *Upstream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upstream.Merge(dst, src)
}
func (m *Upstream) XXX_Size() int {
	return xxx_messageInfo_Upstream.Size(m)
}
func (m *Upstream) XXX_DiscardUnknown() {
	xxx_messageInfo_Upstream.DiscardUnknown(m)
}

var xxx_messageInfo_Upstream proto.InternalMessageInfo

func (m *Upstream) GetUpstreamSpec() *UpstreamSpec {
	if m != nil {
		return m.UpstreamSpec
	}
	return nil
}

func (m *Upstream) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *Upstream) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *Upstream) GetDiscoveryMetadata() *DiscoveryMetadata {
	if m != nil {
		return m.DiscoveryMetadata
	}
	return nil
}

// created by discovery services
type DiscoveryMetadata struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoveryMetadata) Reset()         { *m = DiscoveryMetadata{} }
func (m *DiscoveryMetadata) String() string { return proto.CompactTextString(m) }
func (*DiscoveryMetadata) ProtoMessage()    {}
func (*DiscoveryMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_upstream_afa4af8e0d322f93, []int{1}
}
func (m *DiscoveryMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoveryMetadata.Unmarshal(m, b)
}
func (m *DiscoveryMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoveryMetadata.Marshal(b, m, deterministic)
}
func (dst *DiscoveryMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoveryMetadata.Merge(dst, src)
}
func (m *DiscoveryMetadata) XXX_Size() int {
	return xxx_messageInfo_DiscoveryMetadata.Size(m)
}
func (m *DiscoveryMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoveryMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoveryMetadata proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Upstream)(nil), "gloo.solo.io.Upstream")
	proto.RegisterType((*DiscoveryMetadata)(nil), "gloo.solo.io.DiscoveryMetadata")
}
func (this *Upstream) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Upstream)
	if !ok {
		that2, ok := that.(Upstream)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.UpstreamSpec.Equal(that1.UpstreamSpec) {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.DiscoveryMetadata.Equal(that1.DiscoveryMetadata) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *DiscoveryMetadata) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DiscoveryMetadata)
	if !ok {
		that2, ok := that.(DiscoveryMetadata)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}

func init() { proto.RegisterFile("upstream.proto", fileDescriptor_upstream_afa4af8e0d322f93) }

var fileDescriptor_upstream_afa4af8e0d322f93 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4d, 0x4a, 0x03, 0x31,
	0x14, 0xc7, 0x6d, 0x91, 0x5a, 0x62, 0x2b, 0x34, 0x16, 0xa9, 0x5d, 0x58, 0x99, 0x95, 0x1b, 0x13,
	0xaa, 0x1b, 0x75, 0x53, 0x28, 0x82, 0x2b, 0x5d, 0x4c, 0x71, 0xe3, 0xa6, 0xa4, 0x99, 0x34, 0xc6,
	0x7e, 0xbc, 0x90, 0x64, 0x0a, 0x5e, 0xc6, 0xb5, 0x47, 0xf1, 0x14, 0x5d, 0x78, 0x04, 0x4f, 0x20,
	0x93, 0xc9, 0x0c, 0xad, 0x22, 0xb8, 0x9a, 0xf7, 0xe6, 0xfd, 0xff, 0xbf, 0xf7, 0x11, 0x74, 0x90,
	0x6a, 0xeb, 0x8c, 0x60, 0x0b, 0xa2, 0x0d, 0x38, 0xc0, 0x0d, 0x39, 0x07, 0x20, 0x16, 0xe6, 0x40,
	0x14, 0x74, 0xdb, 0x12, 0x24, 0xf8, 0x02, 0xcd, 0xa2, 0x5c, 0xd3, 0xed, 0x4b, 0xe5, 0x9e, 0xd3,
	0x09, 0xe1, 0xb0, 0xa0, 0x99, 0xf2, 0x5c, 0x41, 0xfe, 0x9d, 0x29, 0x47, 0x99, 0x56, 0x74, 0xd5,
	0xa7, 0x0b, 0xe1, 0x58, 0xc2, 0x1c, 0x0b, 0x16, 0xfa, 0x0f, 0x8b, 0x75, 0xcc, 0xa5, 0x36, 0x18,
	0x9a, 0x7a, 0x9e, 0x4a, 0xb5, 0x0c, 0x69, 0xf4, 0x56, 0x45, 0xf5, 0xc7, 0x30, 0x29, 0x1e, 0xa0,
	0x66, 0x31, 0xf5, 0xd8, 0x6a, 0xc1, 0x3b, 0xd5, 0xd3, 0xca, 0xd9, 0xfe, 0x45, 0x97, 0x6c, 0xce,
	0x4e, 0x0a, 0xf9, 0x48, 0x0b, 0x1e, 0x37, 0xd2, 0x8d, 0x0c, 0xdf, 0xa1, 0x5a, 0xde, 0xac, 0x53,
	0xf3, 0xce, 0x36, 0xe1, 0x60, 0x44, 0xe9, 0x1c, 0xf9, 0xda, 0xf0, 0xf8, 0x63, 0xdd, 0xdb, 0xf9,
	0x5a, 0xf7, 0x5a, 0x4e, 0x58, 0x97, 0xa8, 0xe9, 0xf4, 0x26, 0x52, 0x72, 0x09, 0x46, 0x44, 0x71,
	0xb0, 0xe3, 0x2b, 0x54, 0x2f, 0x16, 0xed, 0xec, 0x79, 0xd4, 0xd1, 0x36, 0xea, 0x3e, 0x54, 0x87,
	0xbb, 0x19, 0x2c, 0x2e, 0xd5, 0xf8, 0x01, 0xe1, 0x44, 0x59, 0x0e, 0x2b, 0x61, 0x5e, 0xc7, 0x25,
	0xa3, 0xee, 0x19, 0xbd, 0xed, 0x45, 0x6e, 0x0b, 0x5d, 0x01, 0x8b, 0x5b, 0xc9, 0xcf, 0x5f, 0xd1,
	0x21, 0x6a, 0xfd, 0xd2, 0x0d, 0x07, 0xef, 0x9f, 0x27, 0x95, 0xa7, 0xeb, 0xbf, 0x6e, 0xaf, 0x0d,
	0xbc, 0x08, 0xee, 0x2c, 0x2d, 0x83, 0xac, 0x2f, 0xd5, 0x33, 0x19, 0x9e, 0x64, 0x52, 0xf3, 0xd7,
	0xbf, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x4f, 0xf7, 0xd2, 0x26, 0x02, 0x00, 0x00,
}
