{
 "title": "Extauth Dashboard",
 "description": "Extauth monitoring and metrics. ",
 "tags": [
  "gloo",
  "dynamic",
  "default"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Authorization Check GRPC Latency Quantiles",
   "type": "graph",
   "description": "This chart shows grpc latency quantiles for extauth in measurements of P99, P95 and P50.",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_server_latency_bucket{ grpc_server_method=\"envoy.service.auth.v3.Authorization/Check\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{ grpc_server_method=\"envoy.service.auth.v3.Authorization/Check\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_io_server_server_latency_bucket{ grpc_server_method=\"envoy.service.auth.v3.Authorization/Check\"}[1m])) by (le))"
    }
   ]
  },
  {
   "title": "Authorization Check GRPC Latency Heatmap",
   "type": "heatmap",
   "description": "Displays the extauth grpc latency calculated as buckets over 1 minute intervals.  The legend at the bottom left can be used as a guide to understand outliers.",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_server_latency_bucket{ grpc_server_method=\"envoy.service.auth.v3.Authorization/Check\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Health Check GRPC Latency Heatmap",
   "type": "heatmap",
   "description": "Displays the extauth grpc latency calculated as buckets over 1 minute intervals.  The legend at the bottom left can be used as a guide to understand outliers.",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(grpc_io_server_server_latency_bucket{ grpc_server_method=\"grpc.health.v1.Health/Check\"}[1m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Health Check GRPC Latency Quantiles",
   "type": "graph",
   "description": "This chart shows grpc latency quantiles for extauth in measurements of P99, P95 and P50.",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_io_server_server_latency_bucket{ grpc_server_method=\"grpc.health.v1.Health/Check\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_io_server_server_latency_bucket{ grpc_server_method=\"grpc.health.v1.Health/Check\"}[1m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_io_server_server_latency_bucket{ grpc_server_method=\"grpc.health.v1.Health/Check\"}[1m])) by (le))"
    }
   ]
  }
 ]
}