{
 "title": "Gloo Overview",
 "tags": [
  "gloo",
  "default"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Envoy control plane status (Gloo deployment)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "LDS sync status",
   "type": "gauge",
   "description": "number of in-sync envoy proxies for the LDS API",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glooe_solo_io_xds_insync{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/envoy.config.listener.v3.Listener\"}"
    },
    {
     "expr": "glooe_solo_io_xds_total_entities{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/envoy.config.listener.v3.Listener\"}"
    }
   ]
  },
  {
   "title": "RDS sync status",
   "type": "gauge",
   "description": "number of in-sync envoy proxies for the RDS API",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glooe_solo_io_xds_insync{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/envoy.config.route.v3.RouteConfiguration\"}"
    },
    {
     "expr": "glooe_solo_io_xds_total_entities{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/envoy.config.route.v3.RouteConfiguration\"}"
    }
   ]
  },
  {
   "title": "CDS sync status",
   "type": "gauge",
   "description": "number of in-sync envoy proxies for the CDS API",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glooe_solo_io_xds_insync{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/envoy.config.cluster.v3.Cluster\"}"
    },
    {
     "expr": "glooe_solo_io_xds_total_entities{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/envoy.config.cluster.v3.Cluster\"}"
    }
   ]
  },
  {
   "title": "EDS sync status",
   "type": "gauge",
   "description": "number of in-sync envoy proxies for the EDS API",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glooe_solo_io_xds_insync{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment\"}"
    },
    {
     "expr": "glooe_solo_io_xds_total_entities{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment\"}"
    }
   ]
  },
  {
   "title": "ExtAuth xDS sync status",
   "type": "gauge",
   "description": "number of in-sync envoy proxies for the ExtAuth server",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glooe_solo_io_xds_insync{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/enterprise.gloo.solo.io.ExtAuthConfig\"}"
    },
    {
     "expr": "glooe_solo_io_xds_total_entities{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/enterprise.gloo.solo.io.ExtAuthConfig\"}"
    }
   ]
  },
  {
   "title": "Rate-Limit xDS sync status",
   "type": "gauge",
   "description": "number of in-sync envoy proxies for the Rate Limiting server",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glooe_solo_io_xds_insync{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/glooe.solo.io.RateLimitConfig\"}"
    },
    {
     "expr": "glooe_solo_io_xds_total_entities{gloo=\"gloo\", namespace=\"$namespace\", resource=\"type.googleapis.com/glooe.solo.io.RateLimitConfig\"}"
    }
   ]
  },
  {
   "title": "Number of resources translated by Gloo to Envoy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "api_gloo_solo_io_translator_resources{proxy_name=\"$namespace.gateway-proxy\"}",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "xDS sync errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "glooe_solo_io_xds_nack{gloo=\"gloo\", namespace=\"$namespace\"}",
     "legendFormat": "NACK"
    },
    {
     "expr": "glooe_solo_io_xds_outofsync{gloo=\"gloo\", namespace=\"$namespace\"}",
     "legendFormat": "Out of sync - {{resource}}"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "# Alert tips\n\nAlert if:\n- any gauge value == 0\n- the value of _listeners_ in _\"Number of resources translated by Gloo to Envoy\"_ == 0\n- any metric in _\"xDS sync errors\"_ is above 0"
   }
  },
  { "title": "Envoy proxies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Number of Envoy servers live",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(envoy_server_live{namespace=\"$namespace\"})",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Envoy control plane connected state",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "envoy_control_plane_connected_state{namespace=\"$namespace\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "RDS update rejected and failures",
   "type": "timeseries",
   "description": "based on the RDS failures and rejected metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(envoy_http_rds_update_failure{envoy_http_conn_manager_prefix=\"http\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "Update failures - {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(envoy_http_rds_update_rejected{envoy_http_conn_manager_prefix=\"http\", namespace=\"$namespace\"}[1m])",
     "legendFormat": "Update rejected - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "LDS update rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "rate(envoy_listener_manager_lds_update_rejected{}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "CDS update rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(envoy_cluster_manager_cds_update_rejected{}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "I/O with the xDS server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(envoy_cluster_upstream_cx_rx_bytes_total{envoy_cluster_name=\"xds_cluster\"}[1m])",
     "legendFormat": "XDS Request Bytes - {{kubernetes_pod_name}}"
    },
    {
     "expr": "rate(envoy_cluster_upstream_cx_tx_bytes_total{envoy_cluster_name=\"xds_cluster\"}[1m])",
     "legendFormat": "XDS Response Bytes - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "# Alert tips\n\nAlert if:\n- any line in the _\"CDS/RDS/LDS update rejected\"_ stays above 0\n- _\"I/O with the xDS server\"_ stays flat above 0\n- Envoy live servers == 0\n- any gauge under _\"Envoy control plane connected state\"_ == 0\n\n---\n\n# Troubleshooting\n- RDS errors: check out the route options (e.g. WAF rules)\n- CDS errors: check out Upstreams parameters (e.g. TLS secrets)\n- LDS errors: check out the VirtualService parameters (e.g. TLS config and secrets)\n\n"
   }
  },
  { "title": "Gloo Validation Webhook", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Valid config",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "validation_gateway_solo_io_valid_config",
     "legendFormat": "Valid config"
    }
   ]
  },
  {
   "title": "Number of recent Validation errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(validation_gateway_solo_io_resources_rejected{gloo=\"gateway\",job=\"kubernetes-pods\",namespace=\"$namespace\"}[1m])",
     "legendFormat": "Resources rejected"
    }
   ]
  },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "options": {
    "content": "# Alert tips\n\nAlert if:\n- valid config gauge == 0\n\n---\n\n# Troubleshooting\n- Run `glooctl check`"
   }
  }
 ]
}