apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gloo
    gloo: gateway
  name: gateway
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.gateway.deployment.replicas }}
  selector:
    matchLabels:
      gloo: gateway
  template:
    metadata:
      labels:
        gloo: gateway
    spec:
      containers:
      - image: "{{ .Values.gateway.deployment.image.repository }}:{{ .Values.gateway.deployment.image.tag }}"
        imagePullPolicy: {{ .Values.gateway.deployment.image.pullPolicy }}
        name: gateway
        args: ["--namespace", "{{.Release.Namespace}}" ]
