// Code generated by protoc-gen-solo-kit. DO NOT EDIT.

package mocks

import (
	"go.uber.org/zap"

	"github.com/mitchellh/hashstructure"
	"github.com/solo-io/solo-kit/pkg/api/v1/resources"
	"github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
)

type FestingSnapshot struct {
	Mocks MocksByNamespace
}

func (s FestingSnapshot) Clone() FestingSnapshot {
	return FestingSnapshot{
		Mocks: s.Mocks.Clone(),
	}
}

func (s FestingSnapshot) snapshotToHash() FestingSnapshot {
	snapshotForHashing := s.Clone()
	for _, mockResource := range snapshotForHashing.Mocks.List() {
		resources.UpdateMetadata(mockResource, func(meta *core.Metadata) {
			meta.ResourceVersion = ""
		})
		mockResource.SetStatus(core.Status{})
	}

	return snapshotForHashing
}

func (s FestingSnapshot) Hash() uint64 {
	return s.hashStruct(s.snapshotToHash())
}

func (s FestingSnapshot) HashFields() []zap.Field {
	snapshotForHashing := s.snapshotToHash()
	var fields []zap.Field
	mocks := s.hashStruct(snapshotForHashing.Mocks.List())
	fields = append(fields, zap.Uint64("mocks", mocks))

	return append(fields, zap.Uint64("snapshotHash", s.hashStruct(snapshotForHashing)))
}

func (s FestingSnapshot) hashStruct(v interface{}) uint64 {
	h, err := hashstructure.Hash(v, nil)
	if err != nil {
		panic(err)
	}
	return h
}
