# In this directory, run the following command to build this builder.
# $ gcloud container builds submit . --config=cloudbuild.yaml
steps:
# Build the docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/dep', '.']
# Run version to make sure that everything is working properly.
- name: 'gcr.io/$PROJECT_ID/dep'
  args: ['version']
images:
- 'gcr.io/$PROJECT_ID/dep' 