ARG ENVOY_IMAGE
ARG BASE_IMAGE

FROM $ENVOY_IMAGE as envoy

FROM $BASE_IMAGE
ARG GOARCH=amd64

COPY --from=envoy /usr/local/bin/envoy /usr/local/bin/envoy

COPY envoyinit-linux-$GOARCH /usr/local/bin/envoyinit

# SDS-specific setup, only used if ENVOY_SIDECAR=true
COPY docker-entrypoint.sh /

USER 10101

ENTRYPOINT [ "/docker-entrypoint.sh"]
CMD []