name: "Upload artifact"

inputs:
  path:
    description: "Path for files to include"
    required: true
  name:
    description: "Base artifact name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Job ID from GH API
      id: get-job-id
      run: |
        jobs=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id}}/attempts/${{ github.run_attempt }}/jobs)
        job_id=$(echo $jobs | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
        echo "job_id=$job_id" >> $GITHUB_OUTPUT
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}-${{ github.run_id }}-${{ steps.get-job-id.outputs.job_id }}
        path: ${{ inputs.path }}
        if-no-files-found: warn