name: "Upload artifact"

inputs:
  path:
    description: "Path for files to include"
    required: true
  name:
    description: "Base artifact name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}-${{ github.run_id }}-${{ github.job_id }}
        path: ${{ inputs.path }}
        if-no-files-found: warn