kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: https-gw
spec:
  gatewayClassName: gloo-gateway
  listeners:
  - protocol: HTTPS
    port: 8443
    name: https
    tls:
      mode: Terminate
      certificateRefs:
        - name: https
          kind: Secret
    allowedRoutes:
      namespaces:
        from: Same
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: https
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN0akNDQVo0Q0FRQXdEUVlKS29aSWh2Y05BUUVMQlFBd0lURVRNQkVHQTFVRUNnd0tZVzU1SUdSdmJXRnAKYmpFS01BZ0dBMVVFQXd3QktqQWVGdzB5TkRBNU1qSXhOak00TURaYUZ3MHlOVEE1TWpJeE5qTTRNRFphTUNFeApDakFJQmdOVkJBTU1BU294RXpBUkJnTlZCQW9NQ21GdWVTQmtiMjFoYVc0d2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEc2REdmY0MmgyYzdSb2JOb0tSZWFRYzFqdUpaWGtwZzFOWER5aFZOK3cKbFdkVDg0UlFhS1RYVVYxZTkwUUVyb2VrbFZnQld5d3A5WlNsUUhzSTc3MTBVVm16N3RhUFRXbWd0WlhHRy9hTApXSDhiMklsdTUrVXhpajB2K2NheUJqWEVuVWJTVFJQYXlkYU11N1hqODNKV0tKSDZ6TzNVK3pwbCt1SXFVc0p3Ck9GOWpWeFNvMWpEMEQvdllObFNiMTFjNWVjWHUrdk9WMzkrUEpmTDFmUjVQNSt0Vnk1cFlKYWtjNDhJMmlWVzAKNmkvcUdtb3lHMGdCdVZZMkZETzFlcndmUmxHMTRSNEdwdXVWbUg2TEFMcWs2bEZSbHpmbHRYVTBJZ0o5dVNvNApjTjFLMlFHTUhmYUF2RHJqL1JReStKdTQ3TENRcTFYRUU1RzJqdlZOMlNhekFnTUJBQUV3RFFZSktvWklodmNOCkFRRUxCUUFEZ2dFQkFKNkNnVXg3d3huLyswK1hJT2FsclZacnh2SXQvc1J4YnVvQ3NvM04zbm50V0g4TmpVRHIKdURIYUgvRktBVkdsSTFPT0NTa2VhVmlHdGpZdXBkL0ZUbUI2b0pEM2F4cUYzMWVHTDNFTWR4aVZkMTJEbEZsbwp2bkJXZGs4d2xLNk9EcHdUTkd2eEgxOVA5WEN6UjZYRXU0SGlXYnNRZ29YaWN6VC9vQzdCM3NqaG5HYkFmUGx5CkdIRWVhNWV6ay9zU053YmhTcmFabzBZOFNuUzFqSHFKSlhuWk1PbmpCLzlqRGJ6VTZoaVN3a1hiNFZSU3B3ZkIKSE43Q2t3d3FjT0JGWUQ3bGg5bDMzVDN1L0RSWDJWY2FOSWRXSlErRUdTSnowYngrMVhGZXh4R3NjNXNtUWVwZwpIUEEwTVU1ZGNnQkxGSUlFUU1BNHYrSXRKN3BpN2pvN3c3dz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRRHNkRHZmNDJoMmM3Um8KYk5vS1JlYVFjMWp1SlpYa3BnMU5YRHloVk4rd2xXZFQ4NFJRYUtUWFVWMWU5MFFFcm9la2xWZ0JXeXdwOVpTbApRSHNJNzcxMFVWbXo3dGFQVFdtZ3RaWEdHL2FMV0g4YjJJbHU1K1V4aWowditjYXlCalhFblViU1RSUGF5ZGFNCnU3WGo4M0pXS0pINnpPM1UrenBsK3VJcVVzSndPRjlqVnhTbzFqRDBEL3ZZTmxTYjExYzVlY1h1K3ZPVjM5K1AKSmZMMWZSNVA1K3RWeTVwWUpha2M0OEkyaVZXMDZpL3FHbW95RzBnQnVWWTJGRE8xZXJ3ZlJsRzE0UjRHcHV1VgptSDZMQUxxazZsRlJsemZsdFhVMElnSjl1U280Y04xSzJRR01IZmFBdkRyai9SUXkrSnU0N0xDUXExWEVFNUcyCmp2Vk4yU2F6QWdNQkFBRUNnZ0VBT1lvZmQrQVM3NkJBYXBqeWhrVjBVZnAvelpQLzRlQTJwSGlwbUdqYTlsR2wKRDF6VytlbzlFdGlON0NvbnR5dnhmaStKZHVzRTJFRVdweEFGNEtyV1k1UFlURnoyZ1hESkgzNlFyK0RtSWdxcgpBOCt4d2ZkVVlyWE5KZnVXU29RUVdZUWNVOWpGMkJ2OXhjbDMvYnlrT2lzdE91YmJpVlNKWlgrandjRFo2QXlZCkM1Zm1CeXpCaERaWTV2NTg0VzZaMUxTUzZFR3ErQWVmd1hDNnoxcVluV2dlYXBrVG5jbEVESk4vVU9tQnJUeW0KaCtxRjdKTUZBWk1xbGVOQ1U1Wk1aUG43TWRPWkt5c20zaTRSUVNXL0NLMEFzWU9hNmx2TEJkZGxEN2k3THdORQpmRzZnUjhiVXZhQWtETTNEY3B3a0QyeURtUVhwSHFDRmZGUWRjT0p4SVFLQmdRRDJTajNtNHRmdFhUT3JvRDZNClM0N24xTVAzdU40WkJHUnZrcnZQbmdIckRQRG43aEhiZDg2MVJJRnN3dG0zWjRzTmk3RnVsWGU5YUdsek1OWHQKQ1NBYkd3UTJLbFZjeEpIYXZsYWlqUWgwVkZtZVlGSHpMNVMzeGxyc3RzNURnMnp2YU5Jd1VqNVpJMUY0a01YVgpHbFFHNU43dldvTjFIQlJ5NTFoN0VJV3dkd0tCZ1FEMXhyZ3ltcHVRYm5tOE1qTHJzYUd5Y0RxbzFCNzhMN2NHCnk0dEVCY2tGaTRKSTVrbjhxYy8wMTlCQ3dyYTBON0lvNkxMYmhhTVJDdFNLRXhVdDE5QXlBdStZd1U3V1JpKysKY0pLVUo3aTBoYXBMMk4zU1FwS3dMUFBLdXpQc2pkOTNmS2ZHNmdNZElnS0ZnUmlNK2JOdlZtTmNVS1pWa2xUMwpMZFNveGxsbXBRS0JnUUNaOVg4TXZmRk5LRjRNZzNlV0xBV0JWcmZLTzM1YkZTdlRzMTVFUXZuZi9ZNzY3UStzCnFoQkZzRFZYejlaWm1CaU10eTZMZWxRSHl5VmdKTDhXRmdaRDYzZU9oSmdvRFprL3JJeHJ3TTN3S21wN1hxcmIKNG5xTkJ5bi9uNmNBL1Q4enljcmErZzZQbWt4cm1kU1Jpb3ZNWTNZWkdmUGpXVkpQSWQ5bHpzWkRzUUtCZ1FDNwpyYVNvMTlFbEtJZURRNTRJeDFzZmhIMzJ3QXh0TFE2SmZOTDYvYVAwdlFTZklHT3RNZ3NmLzlFRHVlYUVsZWRSClAraWNvMTdUTzc3ek5RRStRWWUxT1BLM1poNEttQXdMVTdGS3UwNWJZNXFZVXFHSTF0ZG0rdHlybWVwYm9EYmQKNm0zQUFxQ2dGWUZ4YXhSUlNyaFBzOXNwK2xnYURpVWRuM3k5Nk1FS0ZRS0JnQXZFeDVYYnZ2RDB3d3F6cjcveApTUmM5aDRiQWFuTW8vUnFxaFd6MU9tU2VMaUh4NlhNc0ROSW01bTBjUlRwNUo1UWRicDdycDB2RS9lQU5BekhWCjdJSE5vaVNDeWs2NnU0anJKL3UvRXpPMkx1VmtGNWdSL1RvdU03eVBNVzJGL004U3gvRWc1M1k0NFBSZGpvT3oKQWY5QmUzYjZxMTdDb3ByU3ZVb2xNU09tCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-route
spec:
  parentRefs:
  - name: https-gw
  hostnames:
  - "example.com"
  rules:
  - backendRefs:
    - name: example-svc
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /timeout
    backendRefs:
    - name: example-svc
      port: 8080
---
apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: policy-attached
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: example-route
  options:
    faults:
      abort:
        httpStatus: 500
    timeout: 11s
    # extauth:
    #   configRef:
    #     name: basic-auth
    #     namespace: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: example-svc
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-web-svc
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
#   labels:
#     app.kubernetes.io/name: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx:stable
#     ports:
#     - containerPort: 80
#       name: http-web-svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
          name: http-web-svc
