name: Run Conformance Tests

on:
  # TODO: Trigger on release events too.
  workflow_dispatch:
    inputs:
      image-variant:
        description: "The image variant to use."
        required: true
        type: choice
        options:
          - standard
          - distroless
      version:
        description: "Optional: Specify an existing Gloo Gateway release tag to deploy and test (e.g., 1.17.3). Leave empty to use the default branch."
        required: false
        type: string

jobs:
  run-conformance-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # TODO(tim): Avoid hardcoding versions here. It's a bit tricky based on
        # how this was setup and there's a limited # of dispatch inputs that GH
        # supports. We can revisit this later.
        kube-version:
        - node: 'v1.33.1@sha256:050072256b9a903bd914c0b2866828150cb229cea0efe5892e2b644d5dd3b34f'
          kubectl: 'v1.33.1'
          kind: 'v0.29.0'
          helm: 'v3.17.3'
        image-variant:
          - ${{ inputs.image-variant }}
        version:
          - ${{ inputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Conformance Tests
        uses: ./.github/workflows/composite-actions/kube-gateway-api-conformance-tests

      # TODO(tim): Add support for downloading the test results and creating
      # a pull request whenever a new release > 1.17+ is cut.
