name: Run Conformance Tests

on:
  # TODO: Trigger on release events too.
  workflow_dispatch:
    inputs:
      image-variant:
        description: "The image variant to use."
        required: true
        type: choice
        options:
          - standard
          - distroless
      version:
        description: "Optional: Specify an existing Gloo Gateway release tag to deploy and test (e.g., 1.17.3). Leave empty to use the default branch."
        required: false
        type: string

jobs:
  prepare-kind-version:
    runs-on: ubuntu-latest
    outputs:
      kind-version: ${{ steps.set-kind-version.outputs.kind-version }}
    steps:
      - uses: actions/checkout@v4
      - name: Read max versions
        id: max_versions
        uses: falti/dotenv-action@v1.1.4
        with:
          path: ./.github/workflows/.env/nightly-tests/max_versions.env
      - name: Set kind-version
        id: set-kind-version
        run: |
          JSON='[
            {
              "node": "${{ steps.max_versions.outputs.node_version }}",
              "kubectl": "${{ steps.max_versions.outputs.kubectl_version }}",
              "kind": "${{ steps.max_versions.outputs.kind_version }}",
              "helm": "${{ steps.max_versions.outputs.helm_version }}"
            }
          ]'
          echo "kind-version=$JSON" >> $GITHUB_OUTPUT

  run-conformance-tests:
    needs: prepare-kind-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-variant:
          - ${{ inputs.image-variant }}
        version:
          - ${{ inputs.version }}
        kube-version: ${{ fromJson(needs.prepare-kind-version.outputs.kind-version) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Conformance Tests
        uses: ./.github/workflows/composite-actions/kube-gateway-api-conformance-tests

      # TODO(tim): Add support for downloading the test results and creating
      # a pull request whenever a new release > 1.17+ is cut.
