name: Run Conformance Tests

on:
  # TODO: Trigger on release events too.
  workflow_dispatch:
    inputs:
      image-variant:
        description: "The image variant to use."
        required: true
        type: choice
        options:
          - standard
          - distroless
      version:
        description: "Optional: Specify an existing Gloo Gateway release tag to deploy and test (e.g., 1.17.3). Leave empty to use the default branch."
        required: false
        type: string

jobs:
  run-conformance-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image-variant:
          - ${{ inputs.image-variant }}
        version:
          - ${{ inputs.version }}
        version-files:
          - file: './.github/workflows/.env/pr-tests/versions.env'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v1.1.4
        with:
          path: ${{ matrix.version-files.file }}
          log-variables: true  

      - name: Run Conformance Tests
        uses: ./.github/workflows/composite-actions/kube-gateway-api-conformance-tests
        with:
          kind-version: ${{ steps.dotenv.outputs.kind_version }}
          kubectl-version: ${{ steps.dotenv.outputs.kubectl_version }}
          helm-version: ${{ steps.dotenv.outputs.helm_version }}
          kind-node-version: ${{ steps.dotenv.outputs.node_version }}
          image-variant: ${{ matrix.image-variant }}
          version: ${{ matrix.version }}

      # TODO(tim): Add support for downloading the test results and creating
      # a pull request whenever a new release > 1.17+ is cut.
