name: Update solo-apis
on:
  release:
    types: [created]
jobs:
  publish-apis:
    name: Publish Gloo APIs
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Actions
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}
      - name: Install SSH Deploy key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SOLO_API_DEPLOY_KEY }}
      - name: Set up Go 1.16.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
        id: go
      - name: Install Protoc
        uses: arduino/setup-protoc@v1.1.2
        with:
          version: '3.6.1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          path: gloo
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          repository: solo-io/solo-apis
          path: solo-apis
      - name: Update solo-apis
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          cd solo-apis
          make mod-download update-deps; ./hack/sync-gloo-apis.sh; make generate
          git config --local user.name soloio-bot
          git config --local user.email soloio-bot@github.com
          git add .
          git commit -m "Sync Gloo APIs to ${TAG_NAME}" --allow-empty
          git checkout -B gloo-${TAG_NAME}
          git remote add solo-apis git@github.com:solo-io/solo-apis.git
          git push solo-apis gloo-${TAG_NAME}
