ARG ENVOY_IMAGE
ARG BASE_IMAGE

FROM $ENVOY_IMAGE as envoy

FROM $BASE_IMAGE
ARG GOARCH=amd64

COPY --from=envoy /usr/local/bin/envoy /usr/local/bin/envoy

COPY gloo-linux-$GOARCH /usr/local/bin/gloo

USER 10101

ENTRYPOINT ["/usr/local/bin/gloo"]